package com.lifelight.api.entity;

import java.util.Date;
import java.util.List;

import com.lifelight.common.pageUtil.PageInfo;

public class DeviceDefinition extends PageInfo{

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column device_definition.id
	 * @mbg.generated
	 */
	private Integer id;
	private Integer platformId;
	
	public Integer getPlatformId() {
		return platformId;
	}

	public void setPlatformId(Integer platformId) {
		this.platformId = platformId;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column device_definition.device_firmId
	 * @mbg.generated
	 */
	private Integer deviceFirmid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column device_definition.device_brandId
	 * @mbg.generated
	 */
	private Integer deviceBrandid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column device_definition.definition_name
	 * @mbg.generated
	 */
	private String definitionName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column device_definition.definition_code
	 * @mbg.generated
	 */
	private String definitionCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column device_definition.definition_spec
	 * @mbg.generated
	 */
	private String definitionSpec;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column device_definition.networking_type
	 * @mbg.generated
	 */
	private String networkingType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column device_definition.definition_desc
	 * @mbg.generated
	 */
	private String definitionDesc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column device_definition.type
	 * @mbg.generated
	 */
	private Integer type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column device_definition.create_time
	 * @mbg.generated
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column device_definition.update_time
	 * @mbg.generated
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column device_definition.isDel
	 * @mbg.generated
	 */
	private String isdel;
	
	 /**
      * 厂商名称
      */
    private String deviceFirmName;
    
     /**
      * 品牌名称
      */
    private String deviceBrandName;
	
	/**
     * 检测项目列表
     */
    private List<DeviceDefinitionProject> projectList;

	public String getDeviceFirmName() {
		return deviceFirmName;
	}

	public void setDeviceFirmName(String deviceFirmName) {
		this.deviceFirmName = deviceFirmName;
	}

	public String getDeviceBrandName() {
		return deviceBrandName;
	}

	public void setDeviceBrandName(String deviceBrandName) {
		this.deviceBrandName = deviceBrandName;
	}

	public List<DeviceDefinitionProject> getProjectList() {
		return projectList;
	}

	public void setProjectList(List<DeviceDefinitionProject> projectList) {
		this.projectList = projectList;
	}
	
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column device_definition.id
	 * @return  the value of device_definition.id
	 * @mbg.generated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column device_definition.id
	 * @param id  the value for device_definition.id
	 * @mbg.generated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column device_definition.device_firmId
	 * @return  the value of device_definition.device_firmId
	 * @mbg.generated
	 */
	public Integer getDeviceFirmid() {
		return deviceFirmid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column device_definition.device_firmId
	 * @param deviceFirmid  the value for device_definition.device_firmId
	 * @mbg.generated
	 */
	public void setDeviceFirmid(Integer deviceFirmid) {
		this.deviceFirmid = deviceFirmid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column device_definition.device_brandId
	 * @return  the value of device_definition.device_brandId
	 * @mbg.generated
	 */
	public Integer getDeviceBrandid() {
		return deviceBrandid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column device_definition.device_brandId
	 * @param deviceBrandid  the value for device_definition.device_brandId
	 * @mbg.generated
	 */
	public void setDeviceBrandid(Integer deviceBrandid) {
		this.deviceBrandid = deviceBrandid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column device_definition.definition_name
	 * @return  the value of device_definition.definition_name
	 * @mbg.generated
	 */
	public String getDefinitionName() {
		return definitionName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column device_definition.definition_name
	 * @param definitionName  the value for device_definition.definition_name
	 * @mbg.generated
	 */
	public void setDefinitionName(String definitionName) {
		this.definitionName = definitionName == null ? null : definitionName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column device_definition.definition_code
	 * @return  the value of device_definition.definition_code
	 * @mbg.generated
	 */
	public String getDefinitionCode() {
		return definitionCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column device_definition.definition_code
	 * @param definitionCode  the value for device_definition.definition_code
	 * @mbg.generated
	 */
	public void setDefinitionCode(String definitionCode) {
		this.definitionCode = definitionCode == null ? null : definitionCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column device_definition.definition_spec
	 * @return  the value of device_definition.definition_spec
	 * @mbg.generated
	 */
	public String getDefinitionSpec() {
		return definitionSpec;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column device_definition.definition_spec
	 * @param definitionSpec  the value for device_definition.definition_spec
	 * @mbg.generated
	 */
	public void setDefinitionSpec(String definitionSpec) {
		this.definitionSpec = definitionSpec == null ? null : definitionSpec.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column device_definition.networking_type
	 * @return  the value of device_definition.networking_type
	 * @mbg.generated
	 */
	public String getNetworkingType() {
		return networkingType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column device_definition.networking_type
	 * @param networkingType  the value for device_definition.networking_type
	 * @mbg.generated
	 */
	public void setNetworkingType(String networkingType) {
		this.networkingType = networkingType == null ? null : networkingType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column device_definition.definition_desc
	 * @return  the value of device_definition.definition_desc
	 * @mbg.generated
	 */
	public String getDefinitionDesc() {
		return definitionDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column device_definition.definition_desc
	 * @param definitionDesc  the value for device_definition.definition_desc
	 * @mbg.generated
	 */
	public void setDefinitionDesc(String definitionDesc) {
		this.definitionDesc = definitionDesc == null ? null : definitionDesc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column device_definition.type
	 * @return  the value of device_definition.type
	 * @mbg.generated
	 */
	public Integer getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column device_definition.type
	 * @param type  the value for device_definition.type
	 * @mbg.generated
	 */
	public void setType(Integer type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column device_definition.create_time
	 * @return  the value of device_definition.create_time
	 * @mbg.generated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column device_definition.create_time
	 * @param createTime  the value for device_definition.create_time
	 * @mbg.generated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column device_definition.update_time
	 * @return  the value of device_definition.update_time
	 * @mbg.generated
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column device_definition.update_time
	 * @param updateTime  the value for device_definition.update_time
	 * @mbg.generated
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column device_definition.isDel
	 * @return  the value of device_definition.isDel
	 * @mbg.generated
	 */
	public String getIsdel() {
		return isdel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column device_definition.isDel
	 * @param isdel  the value for device_definition.isDel
	 * @mbg.generated
	 */
	public void setIsdel(String isdel) {
		this.isdel = isdel == null ? null : isdel.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_definition
	 * @mbg.generated
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		DeviceDefinition other = (DeviceDefinition) that;
		return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
				&& (this.getDeviceFirmid() == null ? other.getDeviceFirmid() == null
						: this.getDeviceFirmid().equals(other.getDeviceFirmid()))
				&& (this.getDeviceBrandid() == null ? other.getDeviceBrandid() == null
						: this.getDeviceBrandid().equals(other.getDeviceBrandid()))
				&& (this.getDefinitionName() == null ? other.getDefinitionName() == null
						: this.getDefinitionName().equals(other.getDefinitionName()))
				&& (this.getDefinitionCode() == null ? other.getDefinitionCode() == null
						: this.getDefinitionCode().equals(other.getDefinitionCode()))
				&& (this.getDefinitionSpec() == null ? other.getDefinitionSpec() == null
						: this.getDefinitionSpec().equals(other.getDefinitionSpec()))
				&& (this.getNetworkingType() == null ? other.getNetworkingType() == null
						: this.getNetworkingType().equals(other.getNetworkingType()))
				&& (this.getDefinitionDesc() == null ? other.getDefinitionDesc() == null
						: this.getDefinitionDesc().equals(other.getDefinitionDesc()))
				&& (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
				&& (this.getCreateTime() == null ? other.getCreateTime() == null
						: this.getCreateTime().equals(other.getCreateTime()))
				&& (this.getUpdateTime() == null ? other.getUpdateTime() == null
						: this.getUpdateTime().equals(other.getUpdateTime()))
				&& (this.getIsdel() == null ? other.getIsdel() == null : this.getIsdel().equals(other.getIsdel()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_definition
	 * @mbg.generated
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result + ((getDeviceFirmid() == null) ? 0 : getDeviceFirmid().hashCode());
		result = prime * result + ((getDeviceBrandid() == null) ? 0 : getDeviceBrandid().hashCode());
		result = prime * result + ((getDefinitionName() == null) ? 0 : getDefinitionName().hashCode());
		result = prime * result + ((getDefinitionCode() == null) ? 0 : getDefinitionCode().hashCode());
		result = prime * result + ((getDefinitionSpec() == null) ? 0 : getDefinitionSpec().hashCode());
		result = prime * result + ((getNetworkingType() == null) ? 0 : getNetworkingType().hashCode());
		result = prime * result + ((getDefinitionDesc() == null) ? 0 : getDefinitionDesc().hashCode());
		result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
		result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
		result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
		result = prime * result + ((getIsdel() == null) ? 0 : getIsdel().hashCode());
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_definition
	 * @mbg.generated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", deviceFirmid=").append(deviceFirmid);
		sb.append(", deviceBrandid=").append(deviceBrandid);
		sb.append(", definitionName=").append(definitionName);
		sb.append(", definitionCode=").append(definitionCode);
		sb.append(", definitionSpec=").append(definitionSpec);
		sb.append(", networkingType=").append(networkingType);
		sb.append(", definitionDesc=").append(definitionDesc);
		sb.append(", type=").append(type);
		sb.append(", createTime=").append(createTime);
		sb.append(", updateTime=").append(updateTime);
		sb.append(", isdel=").append(isdel);
		sb.append("]");
		return sb.toString();
	}
}