package com.lifelight.api.entity;

import java.util.Date;

import com.lifelight.common.pageUtil.PageInfo;

public class DeviceBrands extends PageInfo{
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column device_brands.id
	 * @mbg.generated
	 */
	private Integer id;
	private Integer platformId;
	
	public Integer getPlatformId() {
		return platformId;
	}

	public void setPlatformId(Integer platformId) {
		this.platformId = platformId;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column device_brands.device_firmId
	 * @mbg.generated
	 */
	private Integer deviceFirmid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column device_brands.brand_name
	 * @mbg.generated
	 */
	private String brandName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column device_brands.brand_desc
	 * @mbg.generated
	 */
	private String brandDesc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column device_brands.create_time
	 * @mbg.generated
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column device_brands.update_time
	 * @mbg.generated
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column device_brands.isDel
	 * @mbg.generated
	 */
	private String isdel;
	
	private String firmName;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column device_brands.id
	 * @return  the value of device_brands.id
	 * @mbg.generated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column device_brands.id
	 * @param id  the value for device_brands.id
	 * @mbg.generated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column device_brands.device_firmId
	 * @return  the value of device_brands.device_firmId
	 * @mbg.generated
	 */
	public Integer getDeviceFirmid() {
		return deviceFirmid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column device_brands.device_firmId
	 * @param deviceFirmid  the value for device_brands.device_firmId
	 * @mbg.generated
	 */
	public void setDeviceFirmid(Integer deviceFirmid) {
		this.deviceFirmid = deviceFirmid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column device_brands.brand_name
	 * @return  the value of device_brands.brand_name
	 * @mbg.generated
	 */
	public String getBrandName() {
		return brandName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column device_brands.brand_name
	 * @param brandName  the value for device_brands.brand_name
	 * @mbg.generated
	 */
	public void setBrandName(String brandName) {
		this.brandName = brandName == null ? null : brandName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column device_brands.brand_desc
	 * @return  the value of device_brands.brand_desc
	 * @mbg.generated
	 */
	public String getBrandDesc() {
		return brandDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column device_brands.brand_desc
	 * @param brandDesc  the value for device_brands.brand_desc
	 * @mbg.generated
	 */
	public void setBrandDesc(String brandDesc) {
		this.brandDesc = brandDesc == null ? null : brandDesc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column device_brands.create_time
	 * @return  the value of device_brands.create_time
	 * @mbg.generated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column device_brands.create_time
	 * @param createTime  the value for device_brands.create_time
	 * @mbg.generated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column device_brands.update_time
	 * @return  the value of device_brands.update_time
	 * @mbg.generated
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column device_brands.update_time
	 * @param updateTime  the value for device_brands.update_time
	 * @mbg.generated
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column device_brands.isDel
	 * @return  the value of device_brands.isDel
	 * @mbg.generated
	 */
	public String getIsdel() {
		return isdel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column device_brands.isDel
	 * @param isdel  the value for device_brands.isDel
	 * @mbg.generated
	 */
	public void setIsdel(String isdel) {
		this.isdel = isdel == null ? null : isdel.trim();
	}

	public String getFirmName() {
		return firmName;
	}

	public void setFirmName(String firmName) {
		this.firmName = firmName == null ? null : firmName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_brands
	 * @mbg.generated
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		DeviceBrands other = (DeviceBrands) that;
		return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
				&& (this.getDeviceFirmid() == null ? other.getDeviceFirmid() == null
						: this.getDeviceFirmid().equals(other.getDeviceFirmid()))
				&& (this.getBrandName() == null ? other.getBrandName() == null
						: this.getBrandName().equals(other.getBrandName()))
				&& (this.getBrandDesc() == null ? other.getBrandDesc() == null
						: this.getBrandDesc().equals(other.getBrandDesc()))
				&& (this.getCreateTime() == null ? other.getCreateTime() == null
						: this.getCreateTime().equals(other.getCreateTime()))
				&& (this.getUpdateTime() == null ? other.getUpdateTime() == null
						: this.getUpdateTime().equals(other.getUpdateTime()))
				&& (this.getIsdel() == null ? other.getIsdel() == null : this.getIsdel().equals(other.getIsdel()))
				&& (this.getFirmName() == null ? other.getFirmName() == null : this.getFirmName().equals(other.getFirmName()));
	}
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_brands
	 * @mbg.generated
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result + ((getDeviceFirmid() == null) ? 0 : getDeviceFirmid().hashCode());
		result = prime * result + ((getBrandName() == null) ? 0 : getBrandName().hashCode());
		result = prime * result + ((getBrandDesc() == null) ? 0 : getBrandDesc().hashCode());
		result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
		result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
		result = prime * result + ((getIsdel() == null) ? 0 : getIsdel().hashCode());
		result = prime * result + ((getFirmName() == null) ? 0 : getFirmName().hashCode());
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_brands
	 * @mbg.generated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", deviceFirmid=").append(deviceFirmid);
		sb.append(", brandName=").append(brandName);
		sb.append(", brandDesc=").append(brandDesc);
		sb.append(", createTime=").append(createTime);
		sb.append(", updateTime=").append(updateTime);
		sb.append(", isdel=").append(isdel);
		sb.append(", firmName=").append(firmName);
		sb.append("]");
		return sb.toString();
	}
}
