package com.lifelight.dubbo.dao;

import com.lifelight.api.entity.ApiUserInvoice;
import com.lifelight.api.entity.ApiUserInvoiceExample;
import com.lifelight.api.vo.ApiUserInvoiceVO;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ApiUserInvoiceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_user_invoice
     *
     * @mbg.generated
     */
    long countByExample(ApiUserInvoiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_user_invoice
     *
     * @mbg.generated
     */
    int deleteByExample(ApiUserInvoiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_user_invoice
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_user_invoice
     *
     * @mbg.generated
     */
    int insert(ApiUserInvoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_user_invoice
     *
     * @mbg.generated
     */
    int insertSelective(ApiUserInvoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_user_invoice
     *
     * @mbg.generated
     */
    List<ApiUserInvoice> selectByExample(ApiUserInvoiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_user_invoice
     *
     * @mbg.generated
     */
    ApiUserInvoice selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_user_invoice
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ApiUserInvoice record, @Param("example") ApiUserInvoiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_user_invoice
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ApiUserInvoice record, @Param("example") ApiUserInvoiceExample example);

    int updateByPrimaryKeySelective(ApiUserInvoice record);

    int updateByPrimaryKey(ApiUserInvoice record);
    
    /* 查询发票信息 根据用户id*/
    List<ApiUserInvoiceVO> queryInvoiceByManagerId(String managerId);
    /* 插入发票信息*/
    int insertVO(ApiUserInvoiceVO record);
    /* 查询发票信息  根据用户id  发票类型  发票抬头类型*/
    ApiUserInvoice selectByEntity(ApiUserInvoiceVO record);
    
    ApiUserInvoiceVO selectBytimeDesc(String managerId);
    
    
}