package com.lifelight.dubbo.dao;

import java.util.List;
import java.util.Map;
import org.apache.ibatis.annotations.Param;

import com.lifelight.api.entity.ImplementSet;
import com.lifelight.api.entity.ImplementSetExample;
import com.lifelight.api.vo.ImplementSetVO;

public interface ImplementSetMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table implement_set
	 *
	 * @mbg.generated
	 */
	long countByExample(ImplementSetExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table implement_set
	 *
	 * @mbg.generated
	 */
	int deleteByExample(ImplementSetExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table implement_set
	 *
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table implement_set
	 *
	 * @mbg.generated
	 */
	int insert(ImplementSet record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table implement_set
	 *
	 * @mbg.generated
	 */
	int insertSelective(ImplementSet record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table implement_set
	 *
	 * @mbg.generated
	 */
	List<ImplementSet> selectByExample(ImplementSetExample example);

	List<ImplementSetVO> selectByType(Map<String, Object> updateMap);

	int updateInUse(Map<String, Object> updateMap);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table implement_set
	 *
	 * @mbg.generated
	 */
	ImplementSet selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table implement_set
	 *
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("record") ImplementSet record,
			@Param("example") ImplementSetExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table implement_set
	 *
	 * @mbg.generated
	 */
	int updateByExample(@Param("record") ImplementSet record,
			@Param("example") ImplementSetExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table implement_set
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(ImplementSet record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table implement_set
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKey(ImplementSet record);

	// 20171031

	int insertVOSelective(ImplementSetVO record);

	int updateVOSelective(ImplementSetVO record);

	int insertListVO(List<ImplementSetVO> records);

	int updateInUseByParentId(Map<String, Object> updateMap);

	List<ImplementSetVO> selectByEntity(ImplementSet record);
}