package com.lifelight.dubbo.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.lifelight.api.entity.ServicePackage;
import com.lifelight.api.entity.ServicePackageExample;
import com.lifelight.api.vo.ServicePackageVO;

public interface ServicePackageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_package
     *
     * @mbg.generated
     */
    long countByExample(ServicePackageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_package
     *
     * @mbg.generated
     */
    int deleteByExample(ServicePackageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_package
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_package
     *
     * @mbg.generated
     */
    int insert(ServicePackage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_package
     *
     * @mbg.generated
     */
    int insertSelective(ServicePackage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_package
     *
     * @mbg.generated
     */
    List<ServicePackage> selectByExample(ServicePackageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_package
     *
     * @mbg.generated
     */
    ServicePackage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_package
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ServicePackage record, @Param("example") ServicePackageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_package
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ServicePackage record, @Param("example") ServicePackageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_package
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ServicePackage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_package
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ServicePackage record);
    
    int getObjectCountByName(ServicePackage record);
    ServicePackage getServicePackageBy(ServicePackage record);
    List<ServicePackageVO> selectServicePackageListPage(ServicePackage record);
}