package com.lifelight.dubbo.dao;

import com.lifelight.api.entity.Message;
import com.lifelight.api.entity.WeixinConfigure;
import com.lifelight.api.entity.WeixinConfigureExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WeixinConfigureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_configure
     *
     * @mbg.generated
     */
    long countByExample(WeixinConfigureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_configure
     *
     * @mbg.generated
     */
    int deleteByExample(WeixinConfigureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_configure
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_configure
     *
     * @mbg.generated
     */
    int insert(WeixinConfigure record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_configure
     *
     * @mbg.generated
     */
    int insertSelective(WeixinConfigure record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_configure
     *
     * @mbg.generated
     */
    List<WeixinConfigure> selectByExample(WeixinConfigureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_configure
     *
     * @mbg.generated
     */
    WeixinConfigure selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_configure
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") WeixinConfigure record, @Param("example") WeixinConfigureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_configure
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") WeixinConfigure record, @Param("example") WeixinConfigureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_configure
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(WeixinConfigure record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_configure
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(WeixinConfigure record);
    
    List<WeixinConfigure> selectWeixinConfigureListPage(WeixinConfigure record);
    
    List<WeixinConfigure> selectByName(WeixinConfigure record);
}