package com.lifelight.dubbo.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.lifelight.api.entity.XlPersonContract;
import com.lifelight.api.entity.XlPersonContractExample;
import com.lifelight.api.vo.SignStatisticsVO;
import com.lifelight.api.vo.XlPersonContractVO;
import com.lifelight.api.vo.XlPersonDocumentVO;

public interface XlPersonContractMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xl_person_contract
     *
     * @mbg.generated
     */
    long countByExample(XlPersonContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xl_person_contract
     *
     * @mbg.generated
     */
    int deleteByExample(XlPersonContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xl_person_contract
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xl_person_contract
     *
     * @mbg.generated
     */
    int insert(XlPersonContract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xl_person_contract
     *
     * @mbg.generated
     */
    int insertSelective(XlPersonContract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xl_person_contract
     *
     * @mbg.generated
     */
    List<XlPersonContract> selectByExample(XlPersonContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xl_person_contract
     *
     * @mbg.generated
     */
    XlPersonContract selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xl_person_contract
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") XlPersonContract record, @Param("example") XlPersonContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xl_person_contract
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") XlPersonContract record, @Param("example") XlPersonContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xl_person_contract
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(XlPersonContract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xl_person_contract
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(XlPersonContract record);
    
    
    List<XlPersonDocumentVO> selectPersonContractListPage(XlPersonDocumentVO documentVO);
    
    List<XlPersonDocumentVO> selectAllPersonContract(XlPersonDocumentVO documentVO);
    
    XlPersonContractVO selectContract(XlPersonContractVO record);
    
    int updateByDocumentId(XlPersonContractVO record);
    //所有机构
    List<SignStatisticsVO> selectAllOrgCount(SignStatisticsVO statisticVO);
    //有偿签约包数
    int selectPaidCount(SignStatisticsVO statisticVO);
    //有偿签约包 已完成数
    int selectPaidFinishCount(SignStatisticsVO statisticVO);
    // 内含项目总数
    int selectPaidItemCount(SignStatisticsVO statisticVO);
    // 执行项目总数
    int selectPaidItemFinishCount(SignStatisticsVO statisticVO);

    
}