package com.lifelight.dubbo.dao;

import com.lifelight.api.entity.XlPersonContract;
import com.lifelight.api.entity.XlPersonDocument;
import com.lifelight.api.entity.XlPersonSchedule;
import com.lifelight.api.entity.XlPersonScheduleExample;
import com.lifelight.api.vo.XlPersonDocumentVO;
import com.lifelight.api.vo.XlPersonScheduleVO;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface XlPersonScheduleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xl_person_schedule
     *
     * @mbg.generated
     */
    long countByExample(XlPersonScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xl_person_schedule
     *
     * @mbg.generated
     */
    int deleteByExample(XlPersonScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xl_person_schedule
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xl_person_schedule
     *
     * @mbg.generated
     */
    int insert(XlPersonSchedule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xl_person_schedule
     *
     * @mbg.generated
     */
    int insertSelective(XlPersonSchedule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xl_person_schedule
     *
     * @mbg.generated
     */
    List<XlPersonSchedule> selectByExampleWithBLOBs(XlPersonScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xl_person_schedule
     *
     * @mbg.generated
     */
    List<XlPersonSchedule> selectByExample(XlPersonScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xl_person_schedule
     *
     * @mbg.generated
     */
    XlPersonSchedule selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xl_person_schedule
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") XlPersonSchedule record, @Param("example") XlPersonScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xl_person_schedule
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") XlPersonSchedule record, @Param("example") XlPersonScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xl_person_schedule
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") XlPersonSchedule record, @Param("example") XlPersonScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xl_person_schedule
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(XlPersonSchedule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xl_person_schedule
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(XlPersonSchedule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xl_person_schedule
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(XlPersonSchedule record);
    
    int updatByEntity(XlPersonSchedule record);
    
    List<XlPersonDocumentVO> selectPersonScheduleListPage(XlPersonDocumentVO documentVO);
    
    List<XlPersonScheduleVO> selectSchedule(XlPersonScheduleVO record);
    
    List<XlPersonScheduleVO> selectNoFinishSchedule(XlPersonSchedule record);
    
    int deleteByContractId(Integer contractId);

    int selectPersonScheduleFinish(XlPersonDocumentVO documentVO);
    
    int selectPersonScheduleSum(XlPersonDocumentVO documentVO);

    
}