package com.lifelight.dubbo.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.lifelight.api.entity.XlPersonDocument;
import com.lifelight.api.entity.XlPersonDocumentExample;
import com.lifelight.api.vo.ApiContractedUserVO;
import com.lifelight.api.vo.ApiUserInfoVO;
import com.lifelight.api.vo.XlPersonDocumentVO;

public interface XlPersonDocumentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xl_person_document
     *
     * @mbg.generated
     */
    long countByExample(XlPersonDocumentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xl_person_document
     *
     * @mbg.generated
     */
    int deleteByExample(XlPersonDocumentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xl_person_document
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xl_person_document
     *
     * @mbg.generated
     */
    int insert(XlPersonDocument record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xl_person_document
     *
     * @mbg.generated
     */
    int insertSelective(XlPersonDocument record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xl_person_document
     *
     * @mbg.generated
     */
    List<XlPersonDocument> selectByExample(XlPersonDocumentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xl_person_document
     *
     * @mbg.generated
     */
    XlPersonDocumentVO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xl_person_document
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") XlPersonDocument record, @Param("example") XlPersonDocumentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xl_person_document
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") XlPersonDocument record, @Param("example") XlPersonDocumentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xl_person_document
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(XlPersonDocument record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xl_person_document
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(XlPersonDocument record);
    
    
    List<XlPersonDocument> selectPersonDocumentListPage(XlPersonDocumentVO record);

    List<XlPersonDocument> selectDocument(XlPersonDocument record);
    
    ApiUserInfoVO querySignUserByEntityCard(XlPersonDocumentVO record);
    
    List<ApiContractedUserVO> getAllUserByConditionListPage(ApiContractedUserVO apiUserInfo);
    
}