package com.lifelight.api.entity;

import java.io.Serializable;
import java.util.Date;

public class ApiUserInvoice implements Serializable{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_user_invoice.id
     *
     * @mbg.generated
     */
    private Integer id;
    private Integer platformId;
    
    public Integer getPlatformId() {
		return platformId;
	}

	public void setPlatformId(Integer platformId) {
		this.platformId = platformId;
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_user_invoice.manager_id
     *
     * @mbg.generated
     */
    private String managerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_user_invoice.invoice_type
     *
     * @mbg.generated
     */
    private String invoiceType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_user_invoice.invoice_title
     *
     * @mbg.generated
     */
    private String invoiceTitleType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_user_invoice.taxpayer
     *
     * @mbg.generated
     */
    private String taxpayer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_user_invoice.taxpayer_number
     *
     * @mbg.generated
     */
    private String taxpayerNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_user_invoice.ticket_collector_mobile
     *
     * @mbg.generated
     */
    private String ticketCollectorMobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_user_invoice.ticket_collector_email
     *
     * @mbg.generated
     */
    private String ticketCollectorEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_user_invoice.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_user_invoice.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_user_invoice.in_use
     *
     * @mbg.generated
     */
    private Integer inUse;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_user_invoice.id
     *
     * @return the value of api_user_invoice.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_user_invoice.id
     *
     * @param id the value for api_user_invoice.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_user_invoice.manager_id
     *
     * @return the value of api_user_invoice.manager_id
     *
     * @mbg.generated
     */
    public String getManagerId() {
        return managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_user_invoice.manager_id
     *
     * @param managerId the value for api_user_invoice.manager_id
     *
     * @mbg.generated
     */
    public void setManagerId(String managerId) {
        this.managerId = managerId == null ? null : managerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_user_invoice.invoice_type
     *
     * @return the value of api_user_invoice.invoice_type
     *
     * @mbg.generated
     */
    public String getInvoiceType() {
        return invoiceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_user_invoice.invoice_type
     *
     * @param invoiceType the value for api_user_invoice.invoice_type
     *
     * @mbg.generated
     */
    public void setInvoiceType(String invoiceType) {
        this.invoiceType = invoiceType == null ? null : invoiceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_user_invoice.invoice_title
     *
     * @return the value of api_user_invoice.invoice_title
     *
     * @mbg.generated
     */
    public String getInvoiceTitleType() {
        return invoiceTitleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_user_invoice.invoice_title
     *
     * @param invoiceTitle the value for api_user_invoice.invoice_title
     *
     * @mbg.generated
     */
    public void setInvoiceTitleType(String invoiceTitleType) {
        this.invoiceTitleType = invoiceTitleType == null ? null : invoiceTitleType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_user_invoice.taxpayer
     *
     * @return the value of api_user_invoice.taxpayer
     *
     * @mbg.generated
     */
    public String getTaxpayer() {
        return taxpayer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_user_invoice.taxpayer
     *
     * @param taxpayer the value for api_user_invoice.taxpayer
     *
     * @mbg.generated
     */
    public void setTaxpayer(String taxpayer) {
        this.taxpayer = taxpayer == null ? null : taxpayer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_user_invoice.taxpayer_number
     *
     * @return the value of api_user_invoice.taxpayer_number
     *
     * @mbg.generated
     */
    public String getTaxpayerNumber() {
        return taxpayerNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_user_invoice.taxpayer_number
     *
     * @param taxpayerNumber the value for api_user_invoice.taxpayer_number
     *
     * @mbg.generated
     */
    public void setTaxpayerNumber(String taxpayerNumber) {
        this.taxpayerNumber = taxpayerNumber == null ? null : taxpayerNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_user_invoice.ticket_collector_mobile
     *
     * @return the value of api_user_invoice.ticket_collector_mobile
     *
     * @mbg.generated
     */
    public String getTicketCollectorMobile() {
        return ticketCollectorMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_user_invoice.ticket_collector_mobile
     *
     * @param ticketCollectorMobile the value for api_user_invoice.ticket_collector_mobile
     *
     * @mbg.generated
     */
    public void setTicketCollectorMobile(String ticketCollectorMobile) {
        this.ticketCollectorMobile = ticketCollectorMobile == null ? null : ticketCollectorMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_user_invoice.ticket_collector_email
     *
     * @return the value of api_user_invoice.ticket_collector_email
     *
     * @mbg.generated
     */
    public String getTicketCollectorEmail() {
        return ticketCollectorEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_user_invoice.ticket_collector_email
     *
     * @param ticketCollectorEmail the value for api_user_invoice.ticket_collector_email
     *
     * @mbg.generated
     */
    public void setTicketCollectorEmail(String ticketCollectorEmail) {
        this.ticketCollectorEmail = ticketCollectorEmail == null ? null : ticketCollectorEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_user_invoice.create_time
     *
     * @return the value of api_user_invoice.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_user_invoice.create_time
     *
     * @param createTime the value for api_user_invoice.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_user_invoice.update_time
     *
     * @return the value of api_user_invoice.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_user_invoice.update_time
     *
     * @param updateTime the value for api_user_invoice.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_user_invoice.in_use
     *
     * @return the value of api_user_invoice.in_use
     *
     * @mbg.generated
     */
    public Integer getInUse() {
        return inUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_user_invoice.in_use
     *
     * @param inUse the value for api_user_invoice.in_use
     *
     * @mbg.generated
     */
    public void setInUse(Integer inUse) {
        this.inUse = inUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_user_invoice
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ApiUserInvoice other = (ApiUserInvoice) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getManagerId() == null ? other.getManagerId() == null : this.getManagerId().equals(other.getManagerId()))
            && (this.getInvoiceType() == null ? other.getInvoiceType() == null : this.getInvoiceType().equals(other.getInvoiceType()))
            && (this.getInvoiceTitleType() == null ? other.getInvoiceTitleType() == null : this.getInvoiceTitleType().equals(other.getInvoiceTitleType()))
            && (this.getTaxpayer() == null ? other.getTaxpayer() == null : this.getTaxpayer().equals(other.getTaxpayer()))
            && (this.getTaxpayerNumber() == null ? other.getTaxpayerNumber() == null : this.getTaxpayerNumber().equals(other.getTaxpayerNumber()))
            && (this.getTicketCollectorMobile() == null ? other.getTicketCollectorMobile() == null : this.getTicketCollectorMobile().equals(other.getTicketCollectorMobile()))
            && (this.getTicketCollectorEmail() == null ? other.getTicketCollectorEmail() == null : this.getTicketCollectorEmail().equals(other.getTicketCollectorEmail()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getInUse() == null ? other.getInUse() == null : this.getInUse().equals(other.getInUse()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_user_invoice
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getManagerId() == null) ? 0 : getManagerId().hashCode());
        result = prime * result + ((getInvoiceType() == null) ? 0 : getInvoiceType().hashCode());
        result = prime * result + ((getInvoiceTitleType() == null) ? 0 : getInvoiceTitleType().hashCode());
        result = prime * result + ((getTaxpayer() == null) ? 0 : getTaxpayer().hashCode());
        result = prime * result + ((getTaxpayerNumber() == null) ? 0 : getTaxpayerNumber().hashCode());
        result = prime * result + ((getTicketCollectorMobile() == null) ? 0 : getTicketCollectorMobile().hashCode());
        result = prime * result + ((getTicketCollectorEmail() == null) ? 0 : getTicketCollectorEmail().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getInUse() == null) ? 0 : getInUse().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_user_invoice
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", managerId=").append(managerId);
        sb.append(", invoiceType=").append(invoiceType);
        sb.append(", invoiceTitleType=").append(invoiceTitleType);
        sb.append(", taxpayer=").append(taxpayer);
        sb.append(", taxpayerNumber=").append(taxpayerNumber);
        sb.append(", ticketCollectorMobile=").append(ticketCollectorMobile);
        sb.append(", ticketCollectorEmail=").append(ticketCollectorEmail);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", inUse=").append(inUse);
        sb.append("]");
        return sb.toString();
    }
}