package com.lifelight.api.entity;

import java.io.Serializable;

public class Country implements Serializable{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.iso
     *
     * @mbg.generated
     */
    private String iso;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.iso3
     *
     * @mbg.generated
     */
    private String iso3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.name_zh
     *
     * @mbg.generated
     */
    private String nameZh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.nicename
     *
     * @mbg.generated
     */
    private String nicename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.numcode
     *
     * @mbg.generated
     */
    private Short numcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.phonecode
     *
     * @mbg.generated
     */
    private Integer phonecode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.id
     *
     * @return the value of country.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.id
     *
     * @param id the value for country.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.iso
     *
     * @return the value of country.iso
     *
     * @mbg.generated
     */
    public String getIso() {
        return iso;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.iso
     *
     * @param iso the value for country.iso
     *
     * @mbg.generated
     */
    public void setIso(String iso) {
        this.iso = iso == null ? null : iso.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.iso3
     *
     * @return the value of country.iso3
     *
     * @mbg.generated
     */
    public String getIso3() {
        return iso3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.iso3
     *
     * @param iso3 the value for country.iso3
     *
     * @mbg.generated
     */
    public void setIso3(String iso3) {
        this.iso3 = iso3 == null ? null : iso3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.name
     *
     * @return the value of country.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.name
     *
     * @param name the value for country.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.name_zh
     *
     * @return the value of country.name_zh
     *
     * @mbg.generated
     */
    public String getNameZh() {
        return nameZh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.name_zh
     *
     * @param nameZh the value for country.name_zh
     *
     * @mbg.generated
     */
    public void setNameZh(String nameZh) {
        this.nameZh = nameZh == null ? null : nameZh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.nicename
     *
     * @return the value of country.nicename
     *
     * @mbg.generated
     */
    public String getNicename() {
        return nicename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.nicename
     *
     * @param nicename the value for country.nicename
     *
     * @mbg.generated
     */
    public void setNicename(String nicename) {
        this.nicename = nicename == null ? null : nicename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.numcode
     *
     * @return the value of country.numcode
     *
     * @mbg.generated
     */
    public Short getNumcode() {
        return numcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.numcode
     *
     * @param numcode the value for country.numcode
     *
     * @mbg.generated
     */
    public void setNumcode(Short numcode) {
        this.numcode = numcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.phonecode
     *
     * @return the value of country.phonecode
     *
     * @mbg.generated
     */
    public Integer getPhonecode() {
        return phonecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.phonecode
     *
     * @param phonecode the value for country.phonecode
     *
     * @mbg.generated
     */
    public void setPhonecode(Integer phonecode) {
        this.phonecode = phonecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table country
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Country other = (Country) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getIso() == null ? other.getIso() == null : this.getIso().equals(other.getIso()))
            && (this.getIso3() == null ? other.getIso3() == null : this.getIso3().equals(other.getIso3()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getNameZh() == null ? other.getNameZh() == null : this.getNameZh().equals(other.getNameZh()))
            && (this.getNicename() == null ? other.getNicename() == null : this.getNicename().equals(other.getNicename()))
            && (this.getNumcode() == null ? other.getNumcode() == null : this.getNumcode().equals(other.getNumcode()))
            && (this.getPhonecode() == null ? other.getPhonecode() == null : this.getPhonecode().equals(other.getPhonecode()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table country
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getIso() == null) ? 0 : getIso().hashCode());
        result = prime * result + ((getIso3() == null) ? 0 : getIso3().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getNameZh() == null) ? 0 : getNameZh().hashCode());
        result = prime * result + ((getNicename() == null) ? 0 : getNicename().hashCode());
        result = prime * result + ((getNumcode() == null) ? 0 : getNumcode().hashCode());
        result = prime * result + ((getPhonecode() == null) ? 0 : getPhonecode().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table country
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", iso=").append(iso);
        sb.append(", iso3=").append(iso3);
        sb.append(", name=").append(name);
        sb.append(", nameZh=").append(nameZh);
        sb.append(", nicename=").append(nicename);
        sb.append(", numcode=").append(numcode);
        sb.append(", phonecode=").append(phonecode);
        sb.append("]");
        return sb.toString();
    }
}