package com.lifelight.api.entity;

import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.lifelight.common.pageUtil.PageInfo;

public class TemplateManagement extends PageInfo{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template_management.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template_management.template_type
     *
     * @mbg.generated
     */
    private String templateType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template_management.weixin_id
     *
     * @mbg.generated
     */
    private Integer platformId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template_management.in_use
     *
     * @mbg.generated
     */
    private String inUse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template_management.create_time
     *
     * @mbg.generated
     */
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss", timezone = "PRC")
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template_management.update_time
     *
     * @mbg.generated
     */
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss", timezone = "PRC")
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template_management.variable
     *
     * @mbg.generated
     */
    private String variable;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template_management.id
     *
     * @return the value of template_management.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template_management.id
     *
     * @param id the value for template_management.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template_management.template_type
     *
     * @return the value of template_management.template_type
     *
     * @mbg.generated
     */
    public String getTemplateType() {
        return templateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template_management.template_type
     *
     * @param templateType the value for template_management.template_type
     *
     * @mbg.generated
     */
    public void setTemplateType(String templateType) {
        this.templateType = templateType == null ? null : templateType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template_management.weixin_id
     *
     * @return the value of template_management.weixin_id
     *
     * @mbg.generated
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template_management.in_use
     *
     * @return the value of template_management.in_use
     *
     * @mbg.generated
     */
    public String getInUse() {
        return inUse;
    }

    public Integer getPlatformId() {
		return platformId;
	}

	public void setPlatformId(Integer platformId) {
		this.platformId = platformId;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template_management.in_use
     *
     * @param inUse the value for template_management.in_use
     *
     * @mbg.generated
     */
    public void setInUse(String inUse) {
        this.inUse = inUse == null ? null : inUse.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template_management.create_time
     *
     * @return the value of template_management.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template_management.create_time
     *
     * @param createTime the value for template_management.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template_management.update_time
     *
     * @return the value of template_management.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template_management.update_time
     *
     * @param updateTime the value for template_management.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template_management.variable
     *
     * @return the value of template_management.variable
     *
     * @mbg.generated
     */
    public String getVariable() {
        return variable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template_management.variable
     *
     * @param variable the value for template_management.variable
     *
     * @mbg.generated
     */
    public void setVariable(String variable) {
        this.variable = variable == null ? null : variable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_management
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TemplateManagement other = (TemplateManagement) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getTemplateType() == null ? other.getTemplateType() == null : this.getTemplateType().equals(other.getTemplateType()))
            && (this.getInUse() == null ? other.getInUse() == null : this.getInUse().equals(other.getInUse()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getVariable() == null ? other.getVariable() == null : this.getVariable().equals(other.getVariable()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_management
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getTemplateType() == null) ? 0 : getTemplateType().hashCode());
        result = prime * result + ((getInUse() == null) ? 0 : getInUse().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getVariable() == null) ? 0 : getVariable().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_management
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", templateType=").append(templateType);
        sb.append(", inUse=").append(inUse);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", variable=").append(variable);
        sb.append("]");
        return sb.toString();
    }
}