package com.lifelight.api.entity;

import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.lifelight.common.pageUtil.PageInfo;

public class XlPersonContract extends PageInfo{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xl_person_contract.id
     *
     * @mbg.generated
     */
    private Integer id;
    
    private String inUse;
    
    private String variable;
    
    public String getVariable() {
		return variable;
	}

	public void setVariable(String variable) {
		this.variable = variable;
	}

	public String getInUse() {
		return inUse;
	}

	public void setInUse(String inUse) {
		this.inUse = inUse;
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xl_person_contract.document_id
     *
     * @mbg.generated
     */
    private Integer documentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xl_person_contract.is_poor
     *
     * @mbg.generated
     */
    private String isPoor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xl_person_contract.sign_date
     *
     * @mbg.generated
     */
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd", timezone = "PRC")
    private Date signDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xl_person_contract.mobile
     *
     * @mbg.generated
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xl_person_contract.family_count
     *
     * @mbg.generated
     */
    private String familyCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xl_person_contract.sign_mode
     *
     * @mbg.generated
     */
    private String signMode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xl_person_contract.captain_name
     *
     * @mbg.generated
     */
    private String captainName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xl_person_contract.doctor_mobile
     *
     * @mbg.generated
     */
    private String doctorMobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xl_person_contract.health
     *
     * @mbg.generated
     */
    private String health;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xl_person_contract.year
     *
     * @mbg.generated
     */
    private String year;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xl_person_contract.sign_doctor_id
     *
     * @mbg.generated
     */
    private String signDoctorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xl_person_contract.sign_start_date
     *
     * @mbg.generated
     */
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd", timezone = "PRC")
    private Date signStartDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xl_person_contract.sign_end_date
     *
     * @mbg.generated
     */
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd", timezone = "PRC")
    private Date signEndDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xl_person_contract.service_content
     *
     * @mbg.generated
     */
    private String serviceContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xl_person_contract.health_assessment
     *
     * @mbg.generated
     */
    private String healthAssessment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xl_person_contract.arrangement
     *
     * @mbg.generated
     */
    private String arrangement;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xl_person_contract.service_mode
     *
     * @mbg.generated
     */
    private String serviceMode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xl_person_contract.medical_type
     *
     * @mbg.generated
     */
    private String medicalType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xl_person_contract.sign_payment
     *
     * @mbg.generated
     */
    private Double signPayment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xl_person_contract.self_payment
     *
     * @mbg.generated
     */
    private Double selfPayment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xl_person_contract.compensation_payment
     *
     * @mbg.generated
     */
    private Double compensationPayment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xl_person_contract.sign_person_type
     *
     * @mbg.generated
     */
    private String signPersonType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xl_person_contract.service_package
     *
     * @mbg.generated
     */
    private String servicePackage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xl_person_contract.create_time
     *
     * @mbg.generated
     */
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss", timezone = "PRC")
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xl_person_contract.update_time
     *
     * @mbg.generated
     */
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss", timezone = "PRC")
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xl_person_contract.sign_status
     *
     * @mbg.generated
     */
    private String signStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xl_person_contract.finish_status
     *
     * @mbg.generated
     */
    private String finishStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xl_person_contract.audit_status
     *
     * @mbg.generated
     */
    private String auditStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xl_person_contract.id
     *
     * @return the value of xl_person_contract.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xl_person_contract.id
     *
     * @param id the value for xl_person_contract.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xl_person_contract.document_id
     *
     * @return the value of xl_person_contract.document_id
     *
     * @mbg.generated
     */
    public Integer getDocumentId() {
        return documentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xl_person_contract.document_id
     *
     * @param documentId the value for xl_person_contract.document_id
     *
     * @mbg.generated
     */
    public void setDocumentId(Integer documentId) {
        this.documentId = documentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xl_person_contract.is_poor
     *
     * @return the value of xl_person_contract.is_poor
     *
     * @mbg.generated
     */
    public String getIsPoor() {
        return isPoor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xl_person_contract.is_poor
     *
     * @param isPoor the value for xl_person_contract.is_poor
     *
     * @mbg.generated
     */
    public void setIsPoor(String isPoor) {
        this.isPoor = isPoor == null ? null : isPoor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xl_person_contract.sign_date
     *
     * @return the value of xl_person_contract.sign_date
     *
     * @mbg.generated
     */
    public Date getSignDate() {
        return signDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xl_person_contract.sign_date
     *
     * @param signDate the value for xl_person_contract.sign_date
     *
     * @mbg.generated
     */
    public void setSignDate(Date signDate) {
        this.signDate = signDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xl_person_contract.mobile
     *
     * @return the value of xl_person_contract.mobile
     *
     * @mbg.generated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xl_person_contract.mobile
     *
     * @param mobile the value for xl_person_contract.mobile
     *
     * @mbg.generated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xl_person_contract.family_count
     *
     * @return the value of xl_person_contract.family_count
     *
     * @mbg.generated
     */
    public String getFamilyCount() {
        return familyCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xl_person_contract.family_count
     *
     * @param familyCount the value for xl_person_contract.family_count
     *
     * @mbg.generated
     */
    public void setFamilyCount(String familyCount) {
        this.familyCount = familyCount == null ? null : familyCount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xl_person_contract.sign_mode
     *
     * @return the value of xl_person_contract.sign_mode
     *
     * @mbg.generated
     */
    public String getSignMode() {
        return signMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xl_person_contract.sign_mode
     *
     * @param signMode the value for xl_person_contract.sign_mode
     *
     * @mbg.generated
     */
    public void setSignMode(String signMode) {
        this.signMode = signMode == null ? null : signMode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xl_person_contract.captain_name
     *
     * @return the value of xl_person_contract.captain_name
     *
     * @mbg.generated
     */
    public String getCaptainName() {
        return captainName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xl_person_contract.captain_name
     *
     * @param captainName the value for xl_person_contract.captain_name
     *
     * @mbg.generated
     */
    public void setCaptainName(String captainName) {
        this.captainName = captainName == null ? null : captainName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xl_person_contract.doctor_mobile
     *
     * @return the value of xl_person_contract.doctor_mobile
     *
     * @mbg.generated
     */
    public String getDoctorMobile() {
        return doctorMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xl_person_contract.doctor_mobile
     *
     * @param doctorMobile the value for xl_person_contract.doctor_mobile
     *
     * @mbg.generated
     */
    public void setDoctorMobile(String doctorMobile) {
        this.doctorMobile = doctorMobile == null ? null : doctorMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xl_person_contract.health
     *
     * @return the value of xl_person_contract.health
     *
     * @mbg.generated
     */
    public String getHealth() {
        return health;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xl_person_contract.health
     *
     * @param health the value for xl_person_contract.health
     *
     * @mbg.generated
     */
    public void setHealth(String health) {
        this.health = health == null ? null : health.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xl_person_contract.year
     *
     * @return the value of xl_person_contract.year
     *
     * @mbg.generated
     */
    public String getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xl_person_contract.year
     *
     * @param year the value for xl_person_contract.year
     *
     * @mbg.generated
     */
    public void setYear(String year) {
        this.year = year == null ? null : year.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xl_person_contract.sign_doctor_id
     *
     * @return the value of xl_person_contract.sign_doctor_id
     *
     * @mbg.generated
     */
    public String getSignDoctorId() {
        return signDoctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xl_person_contract.sign_doctor_id
     *
     * @param signDoctorId the value for xl_person_contract.sign_doctor_id
     *
     * @mbg.generated
     */
    public void setSignDoctorId(String signDoctorId) {
        this.signDoctorId = signDoctorId == null ? null : signDoctorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xl_person_contract.sign_start_date
     *
     * @return the value of xl_person_contract.sign_start_date
     *
     * @mbg.generated
     */
    public Date getSignStartDate() {
        return signStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xl_person_contract.sign_start_date
     *
     * @param signStartDate the value for xl_person_contract.sign_start_date
     *
     * @mbg.generated
     */
    public void setSignStartDate(Date signStartDate) {
        this.signStartDate = signStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xl_person_contract.sign_end_date
     *
     * @return the value of xl_person_contract.sign_end_date
     *
     * @mbg.generated
     */
    public Date getSignEndDate() {
        return signEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xl_person_contract.sign_end_date
     *
     * @param signEndDate the value for xl_person_contract.sign_end_date
     *
     * @mbg.generated
     */
    public void setSignEndDate(Date signEndDate) {
        this.signEndDate = signEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xl_person_contract.service_content
     *
     * @return the value of xl_person_contract.service_content
     *
     * @mbg.generated
     */
    public String getServiceContent() {
        return serviceContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xl_person_contract.service_content
     *
     * @param serviceContent the value for xl_person_contract.service_content
     *
     * @mbg.generated
     */
    public void setServiceContent(String serviceContent) {
        this.serviceContent = serviceContent == null ? null : serviceContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xl_person_contract.health_assessment
     *
     * @return the value of xl_person_contract.health_assessment
     *
     * @mbg.generated
     */
    public String getHealthAssessment() {
        return healthAssessment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xl_person_contract.health_assessment
     *
     * @param healthAssessment the value for xl_person_contract.health_assessment
     *
     * @mbg.generated
     */
    public void setHealthAssessment(String healthAssessment) {
        this.healthAssessment = healthAssessment == null ? null : healthAssessment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xl_person_contract.arrangement
     *
     * @return the value of xl_person_contract.arrangement
     *
     * @mbg.generated
     */
    public String getArrangement() {
        return arrangement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xl_person_contract.arrangement
     *
     * @param arrangement the value for xl_person_contract.arrangement
     *
     * @mbg.generated
     */
    public void setArrangement(String arrangement) {
        this.arrangement = arrangement == null ? null : arrangement.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xl_person_contract.service_mode
     *
     * @return the value of xl_person_contract.service_mode
     *
     * @mbg.generated
     */
    public String getServiceMode() {
        return serviceMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xl_person_contract.service_mode
     *
     * @param serviceMode the value for xl_person_contract.service_mode
     *
     * @mbg.generated
     */
    public void setServiceMode(String serviceMode) {
        this.serviceMode = serviceMode == null ? null : serviceMode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xl_person_contract.medical_type
     *
     * @return the value of xl_person_contract.medical_type
     *
     * @mbg.generated
     */
    public String getMedicalType() {
        return medicalType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xl_person_contract.medical_type
     *
     * @param medicalType the value for xl_person_contract.medical_type
     *
     * @mbg.generated
     */
    public void setMedicalType(String medicalType) {
        this.medicalType = medicalType == null ? null : medicalType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xl_person_contract.sign_payment
     *
     * @return the value of xl_person_contract.sign_payment
     *
     * @mbg.generated
     */
    public Double getSignPayment() {
        return signPayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xl_person_contract.sign_payment
     *
     * @param signPayment the value for xl_person_contract.sign_payment
     *
     * @mbg.generated
     */
    public void setSignPayment(Double signPayment) {
        this.signPayment = signPayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xl_person_contract.self_payment
     *
     * @return the value of xl_person_contract.self_payment
     *
     * @mbg.generated
     */
    public Double getSelfPayment() {
        return selfPayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xl_person_contract.self_payment
     *
     * @param selfPayment the value for xl_person_contract.self_payment
     *
     * @mbg.generated
     */
    public void setSelfPayment(Double selfPayment) {
        this.selfPayment = selfPayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xl_person_contract.compensation_payment
     *
     * @return the value of xl_person_contract.compensation_payment
     *
     * @mbg.generated
     */
    public Double getCompensationPayment() {
        return compensationPayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xl_person_contract.compensation_payment
     *
     * @param compensationPayment the value for xl_person_contract.compensation_payment
     *
     * @mbg.generated
     */
    public void setCompensationPayment(Double compensationPayment) {
        this.compensationPayment = compensationPayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xl_person_contract.sign_person_type
     *
     * @return the value of xl_person_contract.sign_person_type
     *
     * @mbg.generated
     */
    public String getSignPersonType() {
        return signPersonType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xl_person_contract.sign_person_type
     *
     * @param signPersonType the value for xl_person_contract.sign_person_type
     *
     * @mbg.generated
     */
    public void setSignPersonType(String signPersonType) {
        this.signPersonType = signPersonType == null ? null : signPersonType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xl_person_contract.service_package
     *
     * @return the value of xl_person_contract.service_package
     *
     * @mbg.generated
     */
    public String getServicePackage() {
        return servicePackage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xl_person_contract.service_package
     *
     * @param servicePackage the value for xl_person_contract.service_package
     *
     * @mbg.generated
     */
    public void setServicePackage(String servicePackage) {
        this.servicePackage = servicePackage == null ? null : servicePackage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xl_person_contract.create_time
     *
     * @return the value of xl_person_contract.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xl_person_contract.create_time
     *
     * @param createTime the value for xl_person_contract.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xl_person_contract.update_time
     *
     * @return the value of xl_person_contract.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xl_person_contract.update_time
     *
     * @param updateTime the value for xl_person_contract.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xl_person_contract.sign_status
     *
     * @return the value of xl_person_contract.sign_status
     *
     * @mbg.generated
     */
    public String getSignStatus() {
        return signStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xl_person_contract.sign_status
     *
     * @param signStatus the value for xl_person_contract.sign_status
     *
     * @mbg.generated
     */
    public void setSignStatus(String signStatus) {
        this.signStatus = signStatus == null ? null : signStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xl_person_contract.finish_status
     *
     * @return the value of xl_person_contract.finish_status
     *
     * @mbg.generated
     */
    public String getFinishStatus() {
        return finishStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xl_person_contract.finish_status
     *
     * @param finishStatus the value for xl_person_contract.finish_status
     *
     * @mbg.generated
     */
    public void setFinishStatus(String finishStatus) {
        this.finishStatus = finishStatus == null ? null : finishStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xl_person_contract.audit_status
     *
     * @return the value of xl_person_contract.audit_status
     *
     * @mbg.generated
     */
    public String getAuditStatus() {
        return auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xl_person_contract.audit_status
     *
     * @param auditStatus the value for xl_person_contract.audit_status
     *
     * @mbg.generated
     */
    public void setAuditStatus(String auditStatus) {
        this.auditStatus = auditStatus == null ? null : auditStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xl_person_contract
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        XlPersonContract other = (XlPersonContract) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getDocumentId() == null ? other.getDocumentId() == null : this.getDocumentId().equals(other.getDocumentId()))
            && (this.getIsPoor() == null ? other.getIsPoor() == null : this.getIsPoor().equals(other.getIsPoor()))
            && (this.getSignDate() == null ? other.getSignDate() == null : this.getSignDate().equals(other.getSignDate()))
            && (this.getMobile() == null ? other.getMobile() == null : this.getMobile().equals(other.getMobile()))
            && (this.getFamilyCount() == null ? other.getFamilyCount() == null : this.getFamilyCount().equals(other.getFamilyCount()))
            && (this.getSignMode() == null ? other.getSignMode() == null : this.getSignMode().equals(other.getSignMode()))
            && (this.getCaptainName() == null ? other.getCaptainName() == null : this.getCaptainName().equals(other.getCaptainName()))
            && (this.getDoctorMobile() == null ? other.getDoctorMobile() == null : this.getDoctorMobile().equals(other.getDoctorMobile()))
            && (this.getHealth() == null ? other.getHealth() == null : this.getHealth().equals(other.getHealth()))
            && (this.getYear() == null ? other.getYear() == null : this.getYear().equals(other.getYear()))
            && (this.getSignDoctorId() == null ? other.getSignDoctorId() == null : this.getSignDoctorId().equals(other.getSignDoctorId()))
            && (this.getSignStartDate() == null ? other.getSignStartDate() == null : this.getSignStartDate().equals(other.getSignStartDate()))
            && (this.getSignEndDate() == null ? other.getSignEndDate() == null : this.getSignEndDate().equals(other.getSignEndDate()))
            && (this.getServiceContent() == null ? other.getServiceContent() == null : this.getServiceContent().equals(other.getServiceContent()))
            && (this.getHealthAssessment() == null ? other.getHealthAssessment() == null : this.getHealthAssessment().equals(other.getHealthAssessment()))
            && (this.getArrangement() == null ? other.getArrangement() == null : this.getArrangement().equals(other.getArrangement()))
            && (this.getServiceMode() == null ? other.getServiceMode() == null : this.getServiceMode().equals(other.getServiceMode()))
            && (this.getMedicalType() == null ? other.getMedicalType() == null : this.getMedicalType().equals(other.getMedicalType()))
            && (this.getSignPayment() == null ? other.getSignPayment() == null : this.getSignPayment().equals(other.getSignPayment()))
            && (this.getSelfPayment() == null ? other.getSelfPayment() == null : this.getSelfPayment().equals(other.getSelfPayment()))
            && (this.getCompensationPayment() == null ? other.getCompensationPayment() == null : this.getCompensationPayment().equals(other.getCompensationPayment()))
            && (this.getSignPersonType() == null ? other.getSignPersonType() == null : this.getSignPersonType().equals(other.getSignPersonType()))
            && (this.getServicePackage() == null ? other.getServicePackage() == null : this.getServicePackage().equals(other.getServicePackage()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getSignStatus() == null ? other.getSignStatus() == null : this.getSignStatus().equals(other.getSignStatus()))
            && (this.getFinishStatus() == null ? other.getFinishStatus() == null : this.getFinishStatus().equals(other.getFinishStatus()))
            && (this.getAuditStatus() == null ? other.getAuditStatus() == null : this.getAuditStatus().equals(other.getAuditStatus()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xl_person_contract
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getDocumentId() == null) ? 0 : getDocumentId().hashCode());
        result = prime * result + ((getIsPoor() == null) ? 0 : getIsPoor().hashCode());
        result = prime * result + ((getSignDate() == null) ? 0 : getSignDate().hashCode());
        result = prime * result + ((getMobile() == null) ? 0 : getMobile().hashCode());
        result = prime * result + ((getFamilyCount() == null) ? 0 : getFamilyCount().hashCode());
        result = prime * result + ((getSignMode() == null) ? 0 : getSignMode().hashCode());
        result = prime * result + ((getCaptainName() == null) ? 0 : getCaptainName().hashCode());
        result = prime * result + ((getDoctorMobile() == null) ? 0 : getDoctorMobile().hashCode());
        result = prime * result + ((getHealth() == null) ? 0 : getHealth().hashCode());
        result = prime * result + ((getYear() == null) ? 0 : getYear().hashCode());
        result = prime * result + ((getSignDoctorId() == null) ? 0 : getSignDoctorId().hashCode());
        result = prime * result + ((getSignStartDate() == null) ? 0 : getSignStartDate().hashCode());
        result = prime * result + ((getSignEndDate() == null) ? 0 : getSignEndDate().hashCode());
        result = prime * result + ((getServiceContent() == null) ? 0 : getServiceContent().hashCode());
        result = prime * result + ((getHealthAssessment() == null) ? 0 : getHealthAssessment().hashCode());
        result = prime * result + ((getArrangement() == null) ? 0 : getArrangement().hashCode());
        result = prime * result + ((getServiceMode() == null) ? 0 : getServiceMode().hashCode());
        result = prime * result + ((getMedicalType() == null) ? 0 : getMedicalType().hashCode());
        result = prime * result + ((getSignPayment() == null) ? 0 : getSignPayment().hashCode());
        result = prime * result + ((getSelfPayment() == null) ? 0 : getSelfPayment().hashCode());
        result = prime * result + ((getCompensationPayment() == null) ? 0 : getCompensationPayment().hashCode());
        result = prime * result + ((getSignPersonType() == null) ? 0 : getSignPersonType().hashCode());
        result = prime * result + ((getServicePackage() == null) ? 0 : getServicePackage().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getSignStatus() == null) ? 0 : getSignStatus().hashCode());
        result = prime * result + ((getFinishStatus() == null) ? 0 : getFinishStatus().hashCode());
        result = prime * result + ((getAuditStatus() == null) ? 0 : getAuditStatus().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xl_person_contract
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", documentId=").append(documentId);
        sb.append(", isPoor=").append(isPoor);
        sb.append(", signDate=").append(signDate);
        sb.append(", mobile=").append(mobile);
        sb.append(", familyCount=").append(familyCount);
        sb.append(", signMode=").append(signMode);
        sb.append(", captainName=").append(captainName);
        sb.append(", doctorMobile=").append(doctorMobile);
        sb.append(", health=").append(health);
        sb.append(", year=").append(year);
        sb.append(", signDoctorId=").append(signDoctorId);
        sb.append(", signStartDate=").append(signStartDate);
        sb.append(", signEndDate=").append(signEndDate);
        sb.append(", serviceContent=").append(serviceContent);
        sb.append(", healthAssessment=").append(healthAssessment);
        sb.append(", arrangement=").append(arrangement);
        sb.append(", serviceMode=").append(serviceMode);
        sb.append(", medicalType=").append(medicalType);
        sb.append(", signPayment=").append(signPayment);
        sb.append(", selfPayment=").append(selfPayment);
        sb.append(", compensationPayment=").append(compensationPayment);
        sb.append(", signPersonType=").append(signPersonType);
        sb.append(", servicePackage=").append(servicePackage);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", signStatus=").append(signStatus);
        sb.append(", finishStatus=").append(finishStatus);
        sb.append(", auditStatus=").append(auditStatus);
        sb.append(", variable=").append(variable);
        sb.append("]");
        return sb.toString();
    }
}