package com.lifelight.api.entity;

import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.lifelight.common.pageUtil.PageInfo;

public class XlPersonDocument extends PageInfo{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xl_person_document.id
     *
     * @mbg.generated
     */
    private Integer id;

    private Integer platformId;
    
    private String variable;
    
	public Integer getPlatformId() {
		return platformId;
	}

	public void setPlatformId(Integer platformId) {
		this.platformId = platformId;
	}

	public String getVariable() {
		return variable;
	}

	public void setVariable(String variable) {
		this.variable = variable;
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xl_person_document.manager_id
     *
     * @mbg.generated
     */
    private String managerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xl_person_document.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xl_person_document.sex
     *
     * @mbg.generated
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xl_person_document.card_type
     *
     * @mbg.generated
     */
    private String cardType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xl_person_document.card_num
     *
     * @mbg.generated
     */
    private String cardNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xl_person_document.birthday
     *
     * @mbg.generated
     */
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd", timezone = "PRC")
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xl_person_document.mobile
     *
     * @mbg.generated
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xl_person_document.health_card
     *
     * @mbg.generated
     */
    private String healthCard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xl_person_document.document_id
     *
     * @mbg.generated
     */
    private String documentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xl_person_document.new_farmers_card
     *
     * @mbg.generated
     */
    private String newFarmersCard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xl_person_document.medical_insurance_card
     *
     * @mbg.generated
     */
    private String medicalInsuranceCard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xl_person_document.residential_address
     *
     * @mbg.generated
     */
    private String residentialAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xl_person_document.permanent_address
     *
     * @mbg.generated
     */
    private String permanentAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xl_person_document.work_unit
     *
     * @mbg.generated
     */
    private String workUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xl_person_document.family_relations
     *
     * @mbg.generated
     */
    private String familyRelations;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xl_person_document.contacts_name
     *
     * @mbg.generated
     */
    private String contactsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xl_person_document.contacts_mobile
     *
     * @mbg.generated
     */
    private String contactsMobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xl_person_document.living_state
     *
     * @mbg.generated
     */
    private String livingState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xl_person_document.living_type
     *
     * @mbg.generated
     */
    private String livingType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xl_person_document.registered_residence
     *
     * @mbg.generated
     */
    private String registeredResidence;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xl_person_document.arrive_date
     *
     * @mbg.generated
     */
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd", timezone = "PRC")
    private Date arriveDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xl_person_document.country
     *
     * @mbg.generated
     */
    private String country;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xl_person_document.nation
     *
     * @mbg.generated
     */
    private String nation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xl_person_document.blood_type
     *
     * @mbg.generated
     */
    private String bloodType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xl_person_document.rh
     *
     * @mbg.generated
     */
    private String rh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xl_person_document.degree_education
     *
     * @mbg.generated
     */
    private String degreeEducation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xl_person_document.occupation
     *
     * @mbg.generated
     */
    private String occupation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xl_person_document.marriage_status
     *
     * @mbg.generated
     */
    private String marriageStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xl_person_document.date_marriage
     *
     * @mbg.generated
     */
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd", timezone = "PRC")
    private Date dateMarriage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xl_person_document.document_doctor
     *
     * @mbg.generated
     */
    private String documentDoctor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xl_person_document.document_date
     *
     * @mbg.generated
     */
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd", timezone = "PRC")
    private Date documentDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xl_person_document.medical_costs
     *
     * @mbg.generated
     */
    private Double medicalCosts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xl_person_document.medical_card_number
     *
     * @mbg.generated
     */
    private String medicalCardNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xl_person_document.low_insurance_car
     *
     * @mbg.generated
     */
    private String lowInsuranceCar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xl_person_document.drug_allergy_history
     *
     * @mbg.generated
     */
    private String drugAllergyHistory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xl_person_document.past_history
     *
     * @mbg.generated
     */
    private String pastHistory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xl_person_document.mother_medical_history
     *
     * @mbg.generated
     */
    private String motherMedicalHistory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xl_person_document.father_medical_history
     *
     * @mbg.generated
     */
    private String fatherMedicalHistory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xl_person_document.children_medical_history
     *
     * @mbg.generated
     */
    private String childrenMedicalHistory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xl_person_document.brother_medical_history
     *
     * @mbg.generated
     */
    private String brotherMedicalHistory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xl_person_document.heredity_history
     *
     * @mbg.generated
     */
    private String heredityHistory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xl_person_document.is_disability
     *
     * @mbg.generated
     */
    private String isDisability;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xl_person_document.disability_card
     *
     * @mbg.generated
     */
    private String disabilityCard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xl_person_document.expose_history
     *
     * @mbg.generated
     */
    private String exposeHistory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xl_person_document.operation_history
     *
     * @mbg.generated
     */
    private String operationHistory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xl_person_document.trauma_history
     *
     * @mbg.generated
     */
    private String traumaHistory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xl_person_document.blood_transfusion_history
     *
     * @mbg.generated
     */
    private String bloodTransfusionHistory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xl_person_document.kitchen_exhaust
     *
     * @mbg.generated
     */
    private String kitchenExhaust;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xl_person_document.fuel_type
     *
     * @mbg.generated
     */
    private String fuelType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xl_person_document.water
     *
     * @mbg.generated
     */
    private String water;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xl_person_document.toilet
     *
     * @mbg.generated
     */
    private String toilet;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xl_person_document.livestock
     *
     * @mbg.generated
     */
    private String livestock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xl_person_document.remarks
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xl_person_document.key_crowd_type
     *
     * @mbg.generated
     */
    private String keyCrowdType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xl_person_document.province_code
     *
     * @mbg.generated
     */
    private String provinceCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xl_person_document.city_code
     *
     * @mbg.generated
     */
    private String cityCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xl_person_document.town_code
     *
     * @mbg.generated
     */
    private String townCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xl_person_document.create_time
     *
     * @mbg.generated
     */
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss", timezone = "PRC")
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xl_person_document.update_time
     *
     * @mbg.generated
     */
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss", timezone = "PRC")
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xl_person_document.is_sign
     *
     * @mbg.generated
     */
    private String isSign;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xl_person_document.id
     *
     * @return the value of xl_person_document.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xl_person_document.id
     *
     * @param id the value for xl_person_document.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xl_person_document.manager_id
     *
     * @return the value of xl_person_document.manager_id
     *
     * @mbg.generated
     */
    public String getManagerId() {
        return managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xl_person_document.manager_id
     *
     * @param managerId the value for xl_person_document.manager_id
     *
     * @mbg.generated
     */
    public void setManagerId(String managerId) {
        this.managerId = managerId == null ? null : managerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xl_person_document.name
     *
     * @return the value of xl_person_document.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xl_person_document.name
     *
     * @param name the value for xl_person_document.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xl_person_document.sex
     *
     * @return the value of xl_person_document.sex
     *
     * @mbg.generated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xl_person_document.sex
     *
     * @param sex the value for xl_person_document.sex
     *
     * @mbg.generated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xl_person_document.card_type
     *
     * @return the value of xl_person_document.card_type
     *
     * @mbg.generated
     */
    public String getCardType() {
        return cardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xl_person_document.card_type
     *
     * @param cardType the value for xl_person_document.card_type
     *
     * @mbg.generated
     */
    public void setCardType(String cardType) {
        this.cardType = cardType == null ? null : cardType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xl_person_document.card_num
     *
     * @return the value of xl_person_document.card_num
     *
     * @mbg.generated
     */
    public String getCardNum() {
        return cardNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xl_person_document.card_num
     *
     * @param cardNum the value for xl_person_document.card_num
     *
     * @mbg.generated
     */
    public void setCardNum(String cardNum) {
        this.cardNum = cardNum == null ? null : cardNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xl_person_document.birthday
     *
     * @return the value of xl_person_document.birthday
     *
     * @mbg.generated
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xl_person_document.birthday
     *
     * @param birthday the value for xl_person_document.birthday
     *
     * @mbg.generated
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xl_person_document.mobile
     *
     * @return the value of xl_person_document.mobile
     *
     * @mbg.generated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xl_person_document.mobile
     *
     * @param mobile the value for xl_person_document.mobile
     *
     * @mbg.generated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xl_person_document.health_card
     *
     * @return the value of xl_person_document.health_card
     *
     * @mbg.generated
     */
    public String getHealthCard() {
        return healthCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xl_person_document.health_card
     *
     * @param healthCard the value for xl_person_document.health_card
     *
     * @mbg.generated
     */
    public void setHealthCard(String healthCard) {
        this.healthCard = healthCard == null ? null : healthCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xl_person_document.document_id
     *
     * @return the value of xl_person_document.document_id
     *
     * @mbg.generated
     */
    public String getDocumentId() {
        return documentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xl_person_document.document_id
     *
     * @param documentId the value for xl_person_document.document_id
     *
     * @mbg.generated
     */
    public void setDocumentId(String documentId) {
        this.documentId = documentId == null ? null : documentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xl_person_document.new_farmers_card
     *
     * @return the value of xl_person_document.new_farmers_card
     *
     * @mbg.generated
     */
    public String getNewFarmersCard() {
        return newFarmersCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xl_person_document.new_farmers_card
     *
     * @param newFarmersCard the value for xl_person_document.new_farmers_card
     *
     * @mbg.generated
     */
    public void setNewFarmersCard(String newFarmersCard) {
        this.newFarmersCard = newFarmersCard == null ? null : newFarmersCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xl_person_document.medical_insurance_card
     *
     * @return the value of xl_person_document.medical_insurance_card
     *
     * @mbg.generated
     */
    public String getMedicalInsuranceCard() {
        return medicalInsuranceCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xl_person_document.medical_insurance_card
     *
     * @param medicalInsuranceCard the value for xl_person_document.medical_insurance_card
     *
     * @mbg.generated
     */
    public void setMedicalInsuranceCard(String medicalInsuranceCard) {
        this.medicalInsuranceCard = medicalInsuranceCard == null ? null : medicalInsuranceCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xl_person_document.residential_address
     *
     * @return the value of xl_person_document.residential_address
     *
     * @mbg.generated
     */
    public String getResidentialAddress() {
        return residentialAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xl_person_document.residential_address
     *
     * @param residentialAddress the value for xl_person_document.residential_address
     *
     * @mbg.generated
     */
    public void setResidentialAddress(String residentialAddress) {
        this.residentialAddress = residentialAddress == null ? null : residentialAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xl_person_document.permanent_address
     *
     * @return the value of xl_person_document.permanent_address
     *
     * @mbg.generated
     */
    public String getPermanentAddress() {
        return permanentAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xl_person_document.permanent_address
     *
     * @param permanentAddress the value for xl_person_document.permanent_address
     *
     * @mbg.generated
     */
    public void setPermanentAddress(String permanentAddress) {
        this.permanentAddress = permanentAddress == null ? null : permanentAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xl_person_document.work_unit
     *
     * @return the value of xl_person_document.work_unit
     *
     * @mbg.generated
     */
    public String getWorkUnit() {
        return workUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xl_person_document.work_unit
     *
     * @param workUnit the value for xl_person_document.work_unit
     *
     * @mbg.generated
     */
    public void setWorkUnit(String workUnit) {
        this.workUnit = workUnit == null ? null : workUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xl_person_document.family_relations
     *
     * @return the value of xl_person_document.family_relations
     *
     * @mbg.generated
     */
    public String getFamilyRelations() {
        return familyRelations;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xl_person_document.family_relations
     *
     * @param familyRelations the value for xl_person_document.family_relations
     *
     * @mbg.generated
     */
    public void setFamilyRelations(String familyRelations) {
        this.familyRelations = familyRelations == null ? null : familyRelations.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xl_person_document.contacts_name
     *
     * @return the value of xl_person_document.contacts_name
     *
     * @mbg.generated
     */
    public String getContactsName() {
        return contactsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xl_person_document.contacts_name
     *
     * @param contactsName the value for xl_person_document.contacts_name
     *
     * @mbg.generated
     */
    public void setContactsName(String contactsName) {
        this.contactsName = contactsName == null ? null : contactsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xl_person_document.contacts_mobile
     *
     * @return the value of xl_person_document.contacts_mobile
     *
     * @mbg.generated
     */
    public String getContactsMobile() {
        return contactsMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xl_person_document.contacts_mobile
     *
     * @param contactsMobile the value for xl_person_document.contacts_mobile
     *
     * @mbg.generated
     */
    public void setContactsMobile(String contactsMobile) {
        this.contactsMobile = contactsMobile == null ? null : contactsMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xl_person_document.living_state
     *
     * @return the value of xl_person_document.living_state
     *
     * @mbg.generated
     */
    public String getLivingState() {
        return livingState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xl_person_document.living_state
     *
     * @param livingState the value for xl_person_document.living_state
     *
     * @mbg.generated
     */
    public void setLivingState(String livingState) {
        this.livingState = livingState == null ? null : livingState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xl_person_document.living_type
     *
     * @return the value of xl_person_document.living_type
     *
     * @mbg.generated
     */
    public String getLivingType() {
        return livingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xl_person_document.living_type
     *
     * @param livingType the value for xl_person_document.living_type
     *
     * @mbg.generated
     */
    public void setLivingType(String livingType) {
        this.livingType = livingType == null ? null : livingType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xl_person_document.registered_residence
     *
     * @return the value of xl_person_document.registered_residence
     *
     * @mbg.generated
     */
    public String getRegisteredResidence() {
        return registeredResidence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xl_person_document.registered_residence
     *
     * @param registeredResidence the value for xl_person_document.registered_residence
     *
     * @mbg.generated
     */
    public void setRegisteredResidence(String registeredResidence) {
        this.registeredResidence = registeredResidence == null ? null : registeredResidence.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xl_person_document.arrive_date
     *
     * @return the value of xl_person_document.arrive_date
     *
     * @mbg.generated
     */
    public Date getArriveDate() {
        return arriveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xl_person_document.arrive_date
     *
     * @param arriveDate the value for xl_person_document.arrive_date
     *
     * @mbg.generated
     */
    public void setArriveDate(Date arriveDate) {
        this.arriveDate = arriveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xl_person_document.country
     *
     * @return the value of xl_person_document.country
     *
     * @mbg.generated
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xl_person_document.country
     *
     * @param country the value for xl_person_document.country
     *
     * @mbg.generated
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xl_person_document.nation
     *
     * @return the value of xl_person_document.nation
     *
     * @mbg.generated
     */
    public String getNation() {
        return nation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xl_person_document.nation
     *
     * @param nation the value for xl_person_document.nation
     *
     * @mbg.generated
     */
    public void setNation(String nation) {
        this.nation = nation == null ? null : nation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xl_person_document.blood_type
     *
     * @return the value of xl_person_document.blood_type
     *
     * @mbg.generated
     */
    public String getBloodType() {
        return bloodType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xl_person_document.blood_type
     *
     * @param bloodType the value for xl_person_document.blood_type
     *
     * @mbg.generated
     */
    public void setBloodType(String bloodType) {
        this.bloodType = bloodType == null ? null : bloodType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xl_person_document.rh
     *
     * @return the value of xl_person_document.rh
     *
     * @mbg.generated
     */
    public String getRh() {
        return rh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xl_person_document.rh
     *
     * @param rh the value for xl_person_document.rh
     *
     * @mbg.generated
     */
    public void setRh(String rh) {
        this.rh = rh == null ? null : rh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xl_person_document.degree_education
     *
     * @return the value of xl_person_document.degree_education
     *
     * @mbg.generated
     */
    public String getDegreeEducation() {
        return degreeEducation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xl_person_document.degree_education
     *
     * @param degreeEducation the value for xl_person_document.degree_education
     *
     * @mbg.generated
     */
    public void setDegreeEducation(String degreeEducation) {
        this.degreeEducation = degreeEducation == null ? null : degreeEducation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xl_person_document.occupation
     *
     * @return the value of xl_person_document.occupation
     *
     * @mbg.generated
     */
    public String getOccupation() {
        return occupation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xl_person_document.occupation
     *
     * @param occupation the value for xl_person_document.occupation
     *
     * @mbg.generated
     */
    public void setOccupation(String occupation) {
        this.occupation = occupation == null ? null : occupation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xl_person_document.marriage_status
     *
     * @return the value of xl_person_document.marriage_status
     *
     * @mbg.generated
     */
    public String getMarriageStatus() {
        return marriageStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xl_person_document.marriage_status
     *
     * @param marriageStatus the value for xl_person_document.marriage_status
     *
     * @mbg.generated
     */
    public void setMarriageStatus(String marriageStatus) {
        this.marriageStatus = marriageStatus == null ? null : marriageStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xl_person_document.date_marriage
     *
     * @return the value of xl_person_document.date_marriage
     *
     * @mbg.generated
     */
    public Date getDateMarriage() {
        return dateMarriage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xl_person_document.date_marriage
     *
     * @param dateMarriage the value for xl_person_document.date_marriage
     *
     * @mbg.generated
     */
    public void setDateMarriage(Date dateMarriage) {
        this.dateMarriage = dateMarriage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xl_person_document.document_doctor
     *
     * @return the value of xl_person_document.document_doctor
     *
     * @mbg.generated
     */
    public String getDocumentDoctor() {
        return documentDoctor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xl_person_document.document_doctor
     *
     * @param documentDoctor the value for xl_person_document.document_doctor
     *
     * @mbg.generated
     */
    public void setDocumentDoctor(String documentDoctor) {
        this.documentDoctor = documentDoctor == null ? null : documentDoctor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xl_person_document.document_date
     *
     * @return the value of xl_person_document.document_date
     *
     * @mbg.generated
     */
    public Date getDocumentDate() {
        return documentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xl_person_document.document_date
     *
     * @param documentDate the value for xl_person_document.document_date
     *
     * @mbg.generated
     */
    public void setDocumentDate(Date documentDate) {
        this.documentDate = documentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xl_person_document.medical_costs
     *
     * @return the value of xl_person_document.medical_costs
     *
     * @mbg.generated
     */
    public Double getMedicalCosts() {
        return medicalCosts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xl_person_document.medical_costs
     *
     * @param medicalCosts the value for xl_person_document.medical_costs
     *
     * @mbg.generated
     */
    public void setMedicalCosts(Double medicalCosts) {
        this.medicalCosts = medicalCosts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xl_person_document.medical_card_number
     *
     * @return the value of xl_person_document.medical_card_number
     *
     * @mbg.generated
     */
    public String getMedicalCardNumber() {
        return medicalCardNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xl_person_document.medical_card_number
     *
     * @param medicalCardNumber the value for xl_person_document.medical_card_number
     *
     * @mbg.generated
     */
    public void setMedicalCardNumber(String medicalCardNumber) {
        this.medicalCardNumber = medicalCardNumber == null ? null : medicalCardNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xl_person_document.low_insurance_car
     *
     * @return the value of xl_person_document.low_insurance_car
     *
     * @mbg.generated
     */
    public String getLowInsuranceCar() {
        return lowInsuranceCar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xl_person_document.low_insurance_car
     *
     * @param lowInsuranceCar the value for xl_person_document.low_insurance_car
     *
     * @mbg.generated
     */
    public void setLowInsuranceCar(String lowInsuranceCar) {
        this.lowInsuranceCar = lowInsuranceCar == null ? null : lowInsuranceCar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xl_person_document.drug_allergy_history
     *
     * @return the value of xl_person_document.drug_allergy_history
     *
     * @mbg.generated
     */
    public String getDrugAllergyHistory() {
        return drugAllergyHistory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xl_person_document.drug_allergy_history
     *
     * @param drugAllergyHistory the value for xl_person_document.drug_allergy_history
     *
     * @mbg.generated
     */
    public void setDrugAllergyHistory(String drugAllergyHistory) {
        this.drugAllergyHistory = drugAllergyHistory == null ? null : drugAllergyHistory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xl_person_document.past_history
     *
     * @return the value of xl_person_document.past_history
     *
     * @mbg.generated
     */
    public String getPastHistory() {
        return pastHistory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xl_person_document.past_history
     *
     * @param pastHistory the value for xl_person_document.past_history
     *
     * @mbg.generated
     */
    public void setPastHistory(String pastHistory) {
        this.pastHistory = pastHistory == null ? null : pastHistory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xl_person_document.mother_medical_history
     *
     * @return the value of xl_person_document.mother_medical_history
     *
     * @mbg.generated
     */
    public String getMotherMedicalHistory() {
        return motherMedicalHistory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xl_person_document.mother_medical_history
     *
     * @param motherMedicalHistory the value for xl_person_document.mother_medical_history
     *
     * @mbg.generated
     */
    public void setMotherMedicalHistory(String motherMedicalHistory) {
        this.motherMedicalHistory = motherMedicalHistory == null ? null : motherMedicalHistory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xl_person_document.father_medical_history
     *
     * @return the value of xl_person_document.father_medical_history
     *
     * @mbg.generated
     */
    public String getFatherMedicalHistory() {
        return fatherMedicalHistory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xl_person_document.father_medical_history
     *
     * @param fatherMedicalHistory the value for xl_person_document.father_medical_history
     *
     * @mbg.generated
     */
    public void setFatherMedicalHistory(String fatherMedicalHistory) {
        this.fatherMedicalHistory = fatherMedicalHistory == null ? null : fatherMedicalHistory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xl_person_document.children_medical_history
     *
     * @return the value of xl_person_document.children_medical_history
     *
     * @mbg.generated
     */
    public String getChildrenMedicalHistory() {
        return childrenMedicalHistory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xl_person_document.children_medical_history
     *
     * @param childrenMedicalHistory the value for xl_person_document.children_medical_history
     *
     * @mbg.generated
     */
    public void setChildrenMedicalHistory(String childrenMedicalHistory) {
        this.childrenMedicalHistory = childrenMedicalHistory == null ? null : childrenMedicalHistory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xl_person_document.brother_medical_history
     *
     * @return the value of xl_person_document.brother_medical_history
     *
     * @mbg.generated
     */
    public String getBrotherMedicalHistory() {
        return brotherMedicalHistory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xl_person_document.brother_medical_history
     *
     * @param brotherMedicalHistory the value for xl_person_document.brother_medical_history
     *
     * @mbg.generated
     */
    public void setBrotherMedicalHistory(String brotherMedicalHistory) {
        this.brotherMedicalHistory = brotherMedicalHistory == null ? null : brotherMedicalHistory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xl_person_document.heredity_history
     *
     * @return the value of xl_person_document.heredity_history
     *
     * @mbg.generated
     */
    public String getHeredityHistory() {
        return heredityHistory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xl_person_document.heredity_history
     *
     * @param heredityHistory the value for xl_person_document.heredity_history
     *
     * @mbg.generated
     */
    public void setHeredityHistory(String heredityHistory) {
        this.heredityHistory = heredityHistory == null ? null : heredityHistory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xl_person_document.is_disability
     *
     * @return the value of xl_person_document.is_disability
     *
     * @mbg.generated
     */
    public String getIsDisability() {
        return isDisability;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xl_person_document.is_disability
     *
     * @param isDisability the value for xl_person_document.is_disability
     *
     * @mbg.generated
     */
    public void setIsDisability(String isDisability) {
        this.isDisability = isDisability == null ? null : isDisability.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xl_person_document.disability_card
     *
     * @return the value of xl_person_document.disability_card
     *
     * @mbg.generated
     */
    public String getDisabilityCard() {
        return disabilityCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xl_person_document.disability_card
     *
     * @param disabilityCard the value for xl_person_document.disability_card
     *
     * @mbg.generated
     */
    public void setDisabilityCard(String disabilityCard) {
        this.disabilityCard = disabilityCard == null ? null : disabilityCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xl_person_document.expose_history
     *
     * @return the value of xl_person_document.expose_history
     *
     * @mbg.generated
     */
    public String getExposeHistory() {
        return exposeHistory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xl_person_document.expose_history
     *
     * @param exposeHistory the value for xl_person_document.expose_history
     *
     * @mbg.generated
     */
    public void setExposeHistory(String exposeHistory) {
        this.exposeHistory = exposeHistory == null ? null : exposeHistory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xl_person_document.operation_history
     *
     * @return the value of xl_person_document.operation_history
     *
     * @mbg.generated
     */
    public String getOperationHistory() {
        return operationHistory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xl_person_document.operation_history
     *
     * @param operationHistory the value for xl_person_document.operation_history
     *
     * @mbg.generated
     */
    public void setOperationHistory(String operationHistory) {
        this.operationHistory = operationHistory == null ? null : operationHistory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xl_person_document.trauma_history
     *
     * @return the value of xl_person_document.trauma_history
     *
     * @mbg.generated
     */
    public String getTraumaHistory() {
        return traumaHistory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xl_person_document.trauma_history
     *
     * @param traumaHistory the value for xl_person_document.trauma_history
     *
     * @mbg.generated
     */
    public void setTraumaHistory(String traumaHistory) {
        this.traumaHistory = traumaHistory == null ? null : traumaHistory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xl_person_document.blood_transfusion_history
     *
     * @return the value of xl_person_document.blood_transfusion_history
     *
     * @mbg.generated
     */
    public String getBloodTransfusionHistory() {
        return bloodTransfusionHistory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xl_person_document.blood_transfusion_history
     *
     * @param bloodTransfusionHistory the value for xl_person_document.blood_transfusion_history
     *
     * @mbg.generated
     */
    public void setBloodTransfusionHistory(String bloodTransfusionHistory) {
        this.bloodTransfusionHistory = bloodTransfusionHistory == null ? null : bloodTransfusionHistory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xl_person_document.kitchen_exhaust
     *
     * @return the value of xl_person_document.kitchen_exhaust
     *
     * @mbg.generated
     */
    public String getKitchenExhaust() {
        return kitchenExhaust;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xl_person_document.kitchen_exhaust
     *
     * @param kitchenExhaust the value for xl_person_document.kitchen_exhaust
     *
     * @mbg.generated
     */
    public void setKitchenExhaust(String kitchenExhaust) {
        this.kitchenExhaust = kitchenExhaust == null ? null : kitchenExhaust.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xl_person_document.fuel_type
     *
     * @return the value of xl_person_document.fuel_type
     *
     * @mbg.generated
     */
    public String getFuelType() {
        return fuelType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xl_person_document.fuel_type
     *
     * @param fuelType the value for xl_person_document.fuel_type
     *
     * @mbg.generated
     */
    public void setFuelType(String fuelType) {
        this.fuelType = fuelType == null ? null : fuelType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xl_person_document.water
     *
     * @return the value of xl_person_document.water
     *
     * @mbg.generated
     */
    public String getWater() {
        return water;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xl_person_document.water
     *
     * @param water the value for xl_person_document.water
     *
     * @mbg.generated
     */
    public void setWater(String water) {
        this.water = water == null ? null : water.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xl_person_document.toilet
     *
     * @return the value of xl_person_document.toilet
     *
     * @mbg.generated
     */
    public String getToilet() {
        return toilet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xl_person_document.toilet
     *
     * @param toilet the value for xl_person_document.toilet
     *
     * @mbg.generated
     */
    public void setToilet(String toilet) {
        this.toilet = toilet == null ? null : toilet.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xl_person_document.livestock
     *
     * @return the value of xl_person_document.livestock
     *
     * @mbg.generated
     */
    public String getLivestock() {
        return livestock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xl_person_document.livestock
     *
     * @param livestock the value for xl_person_document.livestock
     *
     * @mbg.generated
     */
    public void setLivestock(String livestock) {
        this.livestock = livestock == null ? null : livestock.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xl_person_document.remarks
     *
     * @return the value of xl_person_document.remarks
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xl_person_document.remarks
     *
     * @param remarks the value for xl_person_document.remarks
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xl_person_document.key_crowd_type
     *
     * @return the value of xl_person_document.key_crowd_type
     *
     * @mbg.generated
     */
    public String getKeyCrowdType() {
        return keyCrowdType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xl_person_document.key_crowd_type
     *
     * @param keyCrowdType the value for xl_person_document.key_crowd_type
     *
     * @mbg.generated
     */
    public void setKeyCrowdType(String keyCrowdType) {
        this.keyCrowdType = keyCrowdType == null ? null : keyCrowdType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xl_person_document.province_code
     *
     * @return the value of xl_person_document.province_code
     *
     * @mbg.generated
     */
    public String getProvinceCode() {
        return provinceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xl_person_document.province_code
     *
     * @param provinceCode the value for xl_person_document.province_code
     *
     * @mbg.generated
     */
    public void setProvinceCode(String provinceCode) {
        this.provinceCode = provinceCode == null ? null : provinceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xl_person_document.city_code
     *
     * @return the value of xl_person_document.city_code
     *
     * @mbg.generated
     */
    public String getCityCode() {
        return cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xl_person_document.city_code
     *
     * @param cityCode the value for xl_person_document.city_code
     *
     * @mbg.generated
     */
    public void setCityCode(String cityCode) {
        this.cityCode = cityCode == null ? null : cityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xl_person_document.town_code
     *
     * @return the value of xl_person_document.town_code
     *
     * @mbg.generated
     */
    public String getTownCode() {
        return townCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xl_person_document.town_code
     *
     * @param townCode the value for xl_person_document.town_code
     *
     * @mbg.generated
     */
    public void setTownCode(String townCode) {
        this.townCode = townCode == null ? null : townCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xl_person_document.create_time
     *
     * @return the value of xl_person_document.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xl_person_document.create_time
     *
     * @param createTime the value for xl_person_document.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xl_person_document.update_time
     *
     * @return the value of xl_person_document.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xl_person_document.update_time
     *
     * @param updateTime the value for xl_person_document.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xl_person_document.is_sign
     *
     * @return the value of xl_person_document.is_sign
     *
     * @mbg.generated
     */
    public String getIsSign() {
        return isSign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xl_person_document.is_sign
     *
     * @param isSign the value for xl_person_document.is_sign
     *
     * @mbg.generated
     */
    public void setIsSign(String isSign) {
        this.isSign = isSign == null ? null : isSign.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xl_person_document
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        XlPersonDocument other = (XlPersonDocument) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getManagerId() == null ? other.getManagerId() == null : this.getManagerId().equals(other.getManagerId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getSex() == null ? other.getSex() == null : this.getSex().equals(other.getSex()))
            && (this.getCardType() == null ? other.getCardType() == null : this.getCardType().equals(other.getCardType()))
            && (this.getCardNum() == null ? other.getCardNum() == null : this.getCardNum().equals(other.getCardNum()))
            && (this.getBirthday() == null ? other.getBirthday() == null : this.getBirthday().equals(other.getBirthday()))
            && (this.getMobile() == null ? other.getMobile() == null : this.getMobile().equals(other.getMobile()))
            && (this.getHealthCard() == null ? other.getHealthCard() == null : this.getHealthCard().equals(other.getHealthCard()))
            && (this.getDocumentId() == null ? other.getDocumentId() == null : this.getDocumentId().equals(other.getDocumentId()))
            && (this.getNewFarmersCard() == null ? other.getNewFarmersCard() == null : this.getNewFarmersCard().equals(other.getNewFarmersCard()))
            && (this.getMedicalInsuranceCard() == null ? other.getMedicalInsuranceCard() == null : this.getMedicalInsuranceCard().equals(other.getMedicalInsuranceCard()))
            && (this.getResidentialAddress() == null ? other.getResidentialAddress() == null : this.getResidentialAddress().equals(other.getResidentialAddress()))
            && (this.getPermanentAddress() == null ? other.getPermanentAddress() == null : this.getPermanentAddress().equals(other.getPermanentAddress()))
            && (this.getWorkUnit() == null ? other.getWorkUnit() == null : this.getWorkUnit().equals(other.getWorkUnit()))
            && (this.getFamilyRelations() == null ? other.getFamilyRelations() == null : this.getFamilyRelations().equals(other.getFamilyRelations()))
            && (this.getContactsName() == null ? other.getContactsName() == null : this.getContactsName().equals(other.getContactsName()))
            && (this.getContactsMobile() == null ? other.getContactsMobile() == null : this.getContactsMobile().equals(other.getContactsMobile()))
            && (this.getLivingState() == null ? other.getLivingState() == null : this.getLivingState().equals(other.getLivingState()))
            && (this.getLivingType() == null ? other.getLivingType() == null : this.getLivingType().equals(other.getLivingType()))
            && (this.getRegisteredResidence() == null ? other.getRegisteredResidence() == null : this.getRegisteredResidence().equals(other.getRegisteredResidence()))
            && (this.getArriveDate() == null ? other.getArriveDate() == null : this.getArriveDate().equals(other.getArriveDate()))
            && (this.getCountry() == null ? other.getCountry() == null : this.getCountry().equals(other.getCountry()))
            && (this.getNation() == null ? other.getNation() == null : this.getNation().equals(other.getNation()))
            && (this.getBloodType() == null ? other.getBloodType() == null : this.getBloodType().equals(other.getBloodType()))
            && (this.getRh() == null ? other.getRh() == null : this.getRh().equals(other.getRh()))
            && (this.getDegreeEducation() == null ? other.getDegreeEducation() == null : this.getDegreeEducation().equals(other.getDegreeEducation()))
            && (this.getOccupation() == null ? other.getOccupation() == null : this.getOccupation().equals(other.getOccupation()))
            && (this.getMarriageStatus() == null ? other.getMarriageStatus() == null : this.getMarriageStatus().equals(other.getMarriageStatus()))
            && (this.getDateMarriage() == null ? other.getDateMarriage() == null : this.getDateMarriage().equals(other.getDateMarriage()))
            && (this.getDocumentDoctor() == null ? other.getDocumentDoctor() == null : this.getDocumentDoctor().equals(other.getDocumentDoctor()))
            && (this.getDocumentDate() == null ? other.getDocumentDate() == null : this.getDocumentDate().equals(other.getDocumentDate()))
            && (this.getMedicalCosts() == null ? other.getMedicalCosts() == null : this.getMedicalCosts().equals(other.getMedicalCosts()))
            && (this.getMedicalCardNumber() == null ? other.getMedicalCardNumber() == null : this.getMedicalCardNumber().equals(other.getMedicalCardNumber()))
            && (this.getLowInsuranceCar() == null ? other.getLowInsuranceCar() == null : this.getLowInsuranceCar().equals(other.getLowInsuranceCar()))
            && (this.getDrugAllergyHistory() == null ? other.getDrugAllergyHistory() == null : this.getDrugAllergyHistory().equals(other.getDrugAllergyHistory()))
            && (this.getPastHistory() == null ? other.getPastHistory() == null : this.getPastHistory().equals(other.getPastHistory()))
            && (this.getMotherMedicalHistory() == null ? other.getMotherMedicalHistory() == null : this.getMotherMedicalHistory().equals(other.getMotherMedicalHistory()))
            && (this.getFatherMedicalHistory() == null ? other.getFatherMedicalHistory() == null : this.getFatherMedicalHistory().equals(other.getFatherMedicalHistory()))
            && (this.getChildrenMedicalHistory() == null ? other.getChildrenMedicalHistory() == null : this.getChildrenMedicalHistory().equals(other.getChildrenMedicalHistory()))
            && (this.getBrotherMedicalHistory() == null ? other.getBrotherMedicalHistory() == null : this.getBrotherMedicalHistory().equals(other.getBrotherMedicalHistory()))
            && (this.getHeredityHistory() == null ? other.getHeredityHistory() == null : this.getHeredityHistory().equals(other.getHeredityHistory()))
            && (this.getIsDisability() == null ? other.getIsDisability() == null : this.getIsDisability().equals(other.getIsDisability()))
            && (this.getDisabilityCard() == null ? other.getDisabilityCard() == null : this.getDisabilityCard().equals(other.getDisabilityCard()))
            && (this.getExposeHistory() == null ? other.getExposeHistory() == null : this.getExposeHistory().equals(other.getExposeHistory()))
            && (this.getOperationHistory() == null ? other.getOperationHistory() == null : this.getOperationHistory().equals(other.getOperationHistory()))
            && (this.getTraumaHistory() == null ? other.getTraumaHistory() == null : this.getTraumaHistory().equals(other.getTraumaHistory()))
            && (this.getBloodTransfusionHistory() == null ? other.getBloodTransfusionHistory() == null : this.getBloodTransfusionHistory().equals(other.getBloodTransfusionHistory()))
            && (this.getKitchenExhaust() == null ? other.getKitchenExhaust() == null : this.getKitchenExhaust().equals(other.getKitchenExhaust()))
            && (this.getFuelType() == null ? other.getFuelType() == null : this.getFuelType().equals(other.getFuelType()))
            && (this.getWater() == null ? other.getWater() == null : this.getWater().equals(other.getWater()))
            && (this.getToilet() == null ? other.getToilet() == null : this.getToilet().equals(other.getToilet()))
            && (this.getLivestock() == null ? other.getLivestock() == null : this.getLivestock().equals(other.getLivestock()))
            && (this.getRemarks() == null ? other.getRemarks() == null : this.getRemarks().equals(other.getRemarks()))
            && (this.getKeyCrowdType() == null ? other.getKeyCrowdType() == null : this.getKeyCrowdType().equals(other.getKeyCrowdType()))
            && (this.getProvinceCode() == null ? other.getProvinceCode() == null : this.getProvinceCode().equals(other.getProvinceCode()))
            && (this.getCityCode() == null ? other.getCityCode() == null : this.getCityCode().equals(other.getCityCode()))
            && (this.getTownCode() == null ? other.getTownCode() == null : this.getTownCode().equals(other.getTownCode()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getIsSign() == null ? other.getIsSign() == null : this.getIsSign().equals(other.getIsSign()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xl_person_document
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getManagerId() == null) ? 0 : getManagerId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getSex() == null) ? 0 : getSex().hashCode());
        result = prime * result + ((getCardType() == null) ? 0 : getCardType().hashCode());
        result = prime * result + ((getCardNum() == null) ? 0 : getCardNum().hashCode());
        result = prime * result + ((getBirthday() == null) ? 0 : getBirthday().hashCode());
        result = prime * result + ((getMobile() == null) ? 0 : getMobile().hashCode());
        result = prime * result + ((getHealthCard() == null) ? 0 : getHealthCard().hashCode());
        result = prime * result + ((getDocumentId() == null) ? 0 : getDocumentId().hashCode());
        result = prime * result + ((getNewFarmersCard() == null) ? 0 : getNewFarmersCard().hashCode());
        result = prime * result + ((getMedicalInsuranceCard() == null) ? 0 : getMedicalInsuranceCard().hashCode());
        result = prime * result + ((getResidentialAddress() == null) ? 0 : getResidentialAddress().hashCode());
        result = prime * result + ((getPermanentAddress() == null) ? 0 : getPermanentAddress().hashCode());
        result = prime * result + ((getWorkUnit() == null) ? 0 : getWorkUnit().hashCode());
        result = prime * result + ((getFamilyRelations() == null) ? 0 : getFamilyRelations().hashCode());
        result = prime * result + ((getContactsName() == null) ? 0 : getContactsName().hashCode());
        result = prime * result + ((getContactsMobile() == null) ? 0 : getContactsMobile().hashCode());
        result = prime * result + ((getLivingState() == null) ? 0 : getLivingState().hashCode());
        result = prime * result + ((getLivingType() == null) ? 0 : getLivingType().hashCode());
        result = prime * result + ((getRegisteredResidence() == null) ? 0 : getRegisteredResidence().hashCode());
        result = prime * result + ((getArriveDate() == null) ? 0 : getArriveDate().hashCode());
        result = prime * result + ((getCountry() == null) ? 0 : getCountry().hashCode());
        result = prime * result + ((getNation() == null) ? 0 : getNation().hashCode());
        result = prime * result + ((getBloodType() == null) ? 0 : getBloodType().hashCode());
        result = prime * result + ((getRh() == null) ? 0 : getRh().hashCode());
        result = prime * result + ((getDegreeEducation() == null) ? 0 : getDegreeEducation().hashCode());
        result = prime * result + ((getOccupation() == null) ? 0 : getOccupation().hashCode());
        result = prime * result + ((getMarriageStatus() == null) ? 0 : getMarriageStatus().hashCode());
        result = prime * result + ((getDateMarriage() == null) ? 0 : getDateMarriage().hashCode());
        result = prime * result + ((getDocumentDoctor() == null) ? 0 : getDocumentDoctor().hashCode());
        result = prime * result + ((getDocumentDate() == null) ? 0 : getDocumentDate().hashCode());
        result = prime * result + ((getMedicalCosts() == null) ? 0 : getMedicalCosts().hashCode());
        result = prime * result + ((getMedicalCardNumber() == null) ? 0 : getMedicalCardNumber().hashCode());
        result = prime * result + ((getLowInsuranceCar() == null) ? 0 : getLowInsuranceCar().hashCode());
        result = prime * result + ((getDrugAllergyHistory() == null) ? 0 : getDrugAllergyHistory().hashCode());
        result = prime * result + ((getPastHistory() == null) ? 0 : getPastHistory().hashCode());
        result = prime * result + ((getMotherMedicalHistory() == null) ? 0 : getMotherMedicalHistory().hashCode());
        result = prime * result + ((getFatherMedicalHistory() == null) ? 0 : getFatherMedicalHistory().hashCode());
        result = prime * result + ((getChildrenMedicalHistory() == null) ? 0 : getChildrenMedicalHistory().hashCode());
        result = prime * result + ((getBrotherMedicalHistory() == null) ? 0 : getBrotherMedicalHistory().hashCode());
        result = prime * result + ((getHeredityHistory() == null) ? 0 : getHeredityHistory().hashCode());
        result = prime * result + ((getIsDisability() == null) ? 0 : getIsDisability().hashCode());
        result = prime * result + ((getDisabilityCard() == null) ? 0 : getDisabilityCard().hashCode());
        result = prime * result + ((getExposeHistory() == null) ? 0 : getExposeHistory().hashCode());
        result = prime * result + ((getOperationHistory() == null) ? 0 : getOperationHistory().hashCode());
        result = prime * result + ((getTraumaHistory() == null) ? 0 : getTraumaHistory().hashCode());
        result = prime * result + ((getBloodTransfusionHistory() == null) ? 0 : getBloodTransfusionHistory().hashCode());
        result = prime * result + ((getKitchenExhaust() == null) ? 0 : getKitchenExhaust().hashCode());
        result = prime * result + ((getFuelType() == null) ? 0 : getFuelType().hashCode());
        result = prime * result + ((getWater() == null) ? 0 : getWater().hashCode());
        result = prime * result + ((getToilet() == null) ? 0 : getToilet().hashCode());
        result = prime * result + ((getLivestock() == null) ? 0 : getLivestock().hashCode());
        result = prime * result + ((getRemarks() == null) ? 0 : getRemarks().hashCode());
        result = prime * result + ((getKeyCrowdType() == null) ? 0 : getKeyCrowdType().hashCode());
        result = prime * result + ((getProvinceCode() == null) ? 0 : getProvinceCode().hashCode());
        result = prime * result + ((getCityCode() == null) ? 0 : getCityCode().hashCode());
        result = prime * result + ((getTownCode() == null) ? 0 : getTownCode().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getIsSign() == null) ? 0 : getIsSign().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xl_person_document
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", managerId=").append(managerId);
        sb.append(", name=").append(name);
        sb.append(", sex=").append(sex);
        sb.append(", cardType=").append(cardType);
        sb.append(", cardNum=").append(cardNum);
        sb.append(", birthday=").append(birthday);
        sb.append(", mobile=").append(mobile);
        sb.append(", healthCard=").append(healthCard);
        sb.append(", documentId=").append(documentId);
        sb.append(", newFarmersCard=").append(newFarmersCard);
        sb.append(", medicalInsuranceCard=").append(medicalInsuranceCard);
        sb.append(", residentialAddress=").append(residentialAddress);
        sb.append(", permanentAddress=").append(permanentAddress);
        sb.append(", workUnit=").append(workUnit);
        sb.append(", familyRelations=").append(familyRelations);
        sb.append(", contactsName=").append(contactsName);
        sb.append(", contactsMobile=").append(contactsMobile);
        sb.append(", livingState=").append(livingState);
        sb.append(", livingType=").append(livingType);
        sb.append(", registeredResidence=").append(registeredResidence);
        sb.append(", arriveDate=").append(arriveDate);
        sb.append(", country=").append(country);
        sb.append(", nation=").append(nation);
        sb.append(", bloodType=").append(bloodType);
        sb.append(", rh=").append(rh);
        sb.append(", degreeEducation=").append(degreeEducation);
        sb.append(", occupation=").append(occupation);
        sb.append(", marriageStatus=").append(marriageStatus);
        sb.append(", dateMarriage=").append(dateMarriage);
        sb.append(", documentDoctor=").append(documentDoctor);
        sb.append(", documentDate=").append(documentDate);
        sb.append(", medicalCosts=").append(medicalCosts);
        sb.append(", medicalCardNumber=").append(medicalCardNumber);
        sb.append(", lowInsuranceCar=").append(lowInsuranceCar);
        sb.append(", drugAllergyHistory=").append(drugAllergyHistory);
        sb.append(", pastHistory=").append(pastHistory);
        sb.append(", motherMedicalHistory=").append(motherMedicalHistory);
        sb.append(", fatherMedicalHistory=").append(fatherMedicalHistory);
        sb.append(", childrenMedicalHistory=").append(childrenMedicalHistory);
        sb.append(", brotherMedicalHistory=").append(brotherMedicalHistory);
        sb.append(", heredityHistory=").append(heredityHistory);
        sb.append(", isDisability=").append(isDisability);
        sb.append(", disabilityCard=").append(disabilityCard);
        sb.append(", exposeHistory=").append(exposeHistory);
        sb.append(", operationHistory=").append(operationHistory);
        sb.append(", traumaHistory=").append(traumaHistory);
        sb.append(", bloodTransfusionHistory=").append(bloodTransfusionHistory);
        sb.append(", kitchenExhaust=").append(kitchenExhaust);
        sb.append(", fuelType=").append(fuelType);
        sb.append(", water=").append(water);
        sb.append(", toilet=").append(toilet);
        sb.append(", livestock=").append(livestock);
        sb.append(", remarks=").append(remarks);
        sb.append(", keyCrowdType=").append(keyCrowdType);
        sb.append(", provinceCode=").append(provinceCode);
        sb.append(", cityCode=").append(cityCode);
        sb.append(", townCode=").append(townCode);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", isSign=").append(isSign);
        sb.append("]");
        return sb.toString();
    }
}