package com.lifelight.dubbo.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.lifelight.api.entity.DeviceDefinition;
import com.lifelight.api.entity.DeviceDefinitionExample;
import com.lifelight.api.vo.DeviceDefinitionVO;

public interface DeviceDefinitionMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_definition
	 * @mbg.generated
	 */
	long countByExample(DeviceDefinitionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_definition
	 * @mbg.generated
	 */
	int deleteByExample(DeviceDefinitionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_definition
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_definition
	 * @mbg.generated
	 */
	int insert(DeviceDefinition record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_definition
	 * @mbg.generated
	 */
	int insertSelective(DeviceDefinition record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_definition
	 * @mbg.generated
	 */
	List<DeviceDefinition> selectByExample(DeviceDefinitionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_definition
	 * @mbg.generated
	 */
	DeviceDefinition selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_definition
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("record") DeviceDefinition record,
			@Param("example") DeviceDefinitionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_definition
	 * @mbg.generated
	 */
	int updateByExample(@Param("record") DeviceDefinition record, @Param("example") DeviceDefinitionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_definition
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(DeviceDefinition record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_definition
	 * @mbg.generated
	 */
	int updateByPrimaryKey(DeviceDefinition record);

	/**
     * 查询总数
     * @param example
     * @return
     */
    long countByEntity(DeviceDefinition entity);
    
    /**
     * 分页查询列表
     * @param entity
     * @return
     */
    List<DeviceDefinitionVO> selectVoByEntity(DeviceDefinition entity);
    
    /**
     * 根据ID 查询对象
     * @param id
     * @return
     */
    DeviceDefinitionVO selectVoById(Integer id);
}