package com.lifelight.dubbo.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.lifelight.api.entity.DeviceDefinitionProject;
import com.lifelight.api.entity.DeviceDefinitionProjectExample;

public interface DeviceDefinitionProjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_definition_project
     *
     * @mbg.generated
     */
    long countByExample(DeviceDefinitionProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_definition_project
     *
     * @mbg.generated
     */
    int deleteByExample(DeviceDefinitionProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_definition_project
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_definition_project
     *
     * @mbg.generated
     */
    int insert(DeviceDefinitionProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_definition_project
     *
     * @mbg.generated
     */
    int insertSelective(DeviceDefinitionProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_definition_project
     *
     * @mbg.generated
     */
    List<DeviceDefinitionProject> selectByExample(DeviceDefinitionProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_definition_project
     *
     * @mbg.generated
     */
    DeviceDefinitionProject selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_definition_project
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DeviceDefinitionProject record, @Param("example") DeviceDefinitionProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_definition_project
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DeviceDefinitionProject record, @Param("example") DeviceDefinitionProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_definition_project
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DeviceDefinitionProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_definition_project
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DeviceDefinitionProject record);
    
    /**
     * 根据设备定义id查询，项目
     * @param definitionId
     * @return
     */
    List<DeviceDefinitionProject> selectByDefinitionId(Integer definitionId);
    
    /**
     * 根据设备定义id删除，项目
     * @param definitionId
     * @return
     */
    int deleteByDefinitionId(Integer definitionId);
    
    /**
     * 批量添加数据
     * @param record
     * @return
     */
    int insertList(List<DeviceDefinitionProject> record);
    
}