package com.lifelight.dubbo.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.lifelight.api.entity.DeviceBrands;
import com.lifelight.api.entity.DeviceBrandsExample;

public interface DeviceBrandsMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_brands
	 * @mbg.generated
	 */
	long countByExample(DeviceBrandsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_brands
	 * @mbg.generated
	 */
	int deleteByExample(DeviceBrandsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_brands
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_brands
	 * @mbg.generated
	 */
	int insert(DeviceBrands record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_brands
	 * @mbg.generated
	 */
	int insertSelective(DeviceBrands record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_brands
	 * @mbg.generated
	 */
	List<DeviceBrands> selectByExample(DeviceBrandsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_brands
	 * @mbg.generated
	 */
	DeviceBrands selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_brands
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("record") DeviceBrands record, @Param("example") DeviceBrandsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_brands
	 * @mbg.generated
	 */
	int updateByExample(@Param("record") DeviceBrands record, @Param("example") DeviceBrandsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_brands
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(DeviceBrands record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_brands
	 * @mbg.generated
	 */
	int updateByPrimaryKey(DeviceBrands record);

	List<DeviceBrands> selectDeviceBrandsListPage(DeviceBrands deviceBrands);
    
	DeviceBrands getDeviceBrandByName(DeviceBrands deviceBrands);
	
	DeviceBrands getDeviceBrandById(Integer id);
	
	int getDeviceBrandsByFirmsId(DeviceBrands deviceBrands);
	
	DeviceBrands getDeviceBrandBy(DeviceBrands deviceBrands);
}