package com.lifelight.api.entity;

import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.lifelight.common.pageUtil.PageInfo;

public class Procedure extends PageInfo{

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column procedure.id
	 * @mbg.generated
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column procedure.manager_id
	 * @mbg.generated
	 */
	private String managerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column procedure.title
	 * @mbg.generated
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column procedure.status
	 * @mbg.generated
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column procedure.share_from
	 * @mbg.generated
	 */
	private String shareFrom;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column procedure.create_time
	 * @mbg.generated
	 */
	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss", timezone = "PRC")
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column procedure.update_time
	 * @mbg.generated
	 */
	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss", timezone = "PRC")
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column procedure.in_use
	 * @mbg.generated
	 */
	private Integer inUse;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column procedure.content
	 * @mbg.generated
	 */
	private String content;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column procedure.id
	 * @return  the value of procedure.id
	 * @mbg.generated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column procedure.id
	 * @param id  the value for procedure.id
	 * @mbg.generated
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column procedure.manager_id
	 * @return  the value of procedure.manager_id
	 * @mbg.generated
	 */
	public String getManagerId() {
		return managerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column procedure.manager_id
	 * @param managerId  the value for procedure.manager_id
	 * @mbg.generated
	 */
	public void setManagerId(String managerId) {
		this.managerId = managerId == null ? null : managerId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column procedure.title
	 * @return  the value of procedure.title
	 * @mbg.generated
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column procedure.title
	 * @param title  the value for procedure.title
	 * @mbg.generated
	 */
	public void setTitle(String title) {
		this.title = title == null ? null : title.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column procedure.status
	 * @return  the value of procedure.status
	 * @mbg.generated
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column procedure.status
	 * @param status  the value for procedure.status
	 * @mbg.generated
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column procedure.share_from
	 * @return  the value of procedure.share_from
	 * @mbg.generated
	 */
	public String getShareFrom() {
		return shareFrom;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column procedure.share_from
	 * @param shareFrom  the value for procedure.share_from
	 * @mbg.generated
	 */
	public void setShareFrom(String shareFrom) {
		this.shareFrom = shareFrom == null ? null : shareFrom.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column procedure.create_time
	 * @return  the value of procedure.create_time
	 * @mbg.generated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column procedure.create_time
	 * @param createTime  the value for procedure.create_time
	 * @mbg.generated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column procedure.update_time
	 * @return  the value of procedure.update_time
	 * @mbg.generated
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column procedure.update_time
	 * @param updateTime  the value for procedure.update_time
	 * @mbg.generated
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column procedure.in_use
	 * @return  the value of procedure.in_use
	 * @mbg.generated
	 */
	public Integer getInUse() {
		return inUse;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column procedure.in_use
	 * @param inUse  the value for procedure.in_use
	 * @mbg.generated
	 */
	public void setInUse(Integer inUse) {
		this.inUse = inUse;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column procedure.content
	 * @return  the value of procedure.content
	 * @mbg.generated
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column procedure.content
	 * @param content  the value for procedure.content
	 * @mbg.generated
	 */
	public void setContent(String content) {
		this.content = content == null ? null : content.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table procedure
	 * @mbg.generated
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		Procedure other = (Procedure) that;
		return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
				&& (this.getManagerId() == null ? other.getManagerId() == null
						: this.getManagerId().equals(other.getManagerId()))
				&& (this.getTitle() == null ? other.getTitle() == null : this.getTitle().equals(other.getTitle()))
				&& (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
				&& (this.getShareFrom() == null ? other.getShareFrom() == null
						: this.getShareFrom().equals(other.getShareFrom()))
				&& (this.getCreateTime() == null ? other.getCreateTime() == null
						: this.getCreateTime().equals(other.getCreateTime()))
				&& (this.getUpdateTime() == null ? other.getUpdateTime() == null
						: this.getUpdateTime().equals(other.getUpdateTime()))
				&& (this.getInUse() == null ? other.getInUse() == null : this.getInUse().equals(other.getInUse()))
				&& (this.getContent() == null ? other.getContent() == null
						: this.getContent().equals(other.getContent()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table procedure
	 * @mbg.generated
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result + ((getManagerId() == null) ? 0 : getManagerId().hashCode());
		result = prime * result + ((getTitle() == null) ? 0 : getTitle().hashCode());
		result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
		result = prime * result + ((getShareFrom() == null) ? 0 : getShareFrom().hashCode());
		result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
		result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
		result = prime * result + ((getInUse() == null) ? 0 : getInUse().hashCode());
		result = prime * result + ((getContent() == null) ? 0 : getContent().hashCode());
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table procedure
	 * @mbg.generated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", managerId=").append(managerId);
		sb.append(", title=").append(title);
		sb.append(", status=").append(status);
		sb.append(", shareFrom=").append(shareFrom);
		sb.append(", createTime=").append(createTime);
		sb.append(", updateTime=").append(updateTime);
		sb.append(", inUse=").append(inUse);
		sb.append(", content=").append(content);
		sb.append("]");
		return sb.toString();
	}

	/**
	 * 
	 */
	private static final long serialVersionUID = 4464829547962235013L;
}