package com.lifelight.api.entity;

import java.io.Serializable;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;

public class ProcedureDialog implements Serializable{
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column procedure_dialog.id
	 * @mbg.generated
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column procedure_dialog.dialog_id
	 * @mbg.generated
	 */
	private String dialogId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column procedure_dialog.procedure_id
	 * @mbg.generated
	 */
	private String procedureId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column procedure_dialog.manager_id
	 * @mbg.generated
	 */
	private String managerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column procedure_dialog.key
	 * @mbg.generated
	 */
	private String key;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column procedure_dialog.data
	 * @mbg.generated
	 */
	private String data;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column procedure_dialog.create_time
	 * @mbg.generated
	 */
	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss", timezone = "PRC")
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column procedure_dialog.update_time
	 * @mbg.generated
	 */
	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss", timezone = "PRC")
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column procedure_dialog.in_use
	 * @mbg.generated
	 */
	private Integer inUse;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column procedure_dialog.id
	 * @return  the value of procedure_dialog.id
	 * @mbg.generated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column procedure_dialog.id
	 * @param id  the value for procedure_dialog.id
	 * @mbg.generated
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column procedure_dialog.dialog_id
	 * @return  the value of procedure_dialog.dialog_id
	 * @mbg.generated
	 */
	public String getDialogId() {
		return dialogId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column procedure_dialog.dialog_id
	 * @param dialogId  the value for procedure_dialog.dialog_id
	 * @mbg.generated
	 */
	public void setDialogId(String dialogId) {
		this.dialogId = dialogId == null ? null : dialogId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column procedure_dialog.procedure_id
	 * @return  the value of procedure_dialog.procedure_id
	 * @mbg.generated
	 */
	public String getProcedureId() {
		return procedureId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column procedure_dialog.procedure_id
	 * @param procedureId  the value for procedure_dialog.procedure_id
	 * @mbg.generated
	 */
	public void setProcedureId(String procedureId) {
		this.procedureId = procedureId == null ? null : procedureId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column procedure_dialog.manager_id
	 * @return  the value of procedure_dialog.manager_id
	 * @mbg.generated
	 */
	public String getManagerId() {
		return managerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column procedure_dialog.manager_id
	 * @param managerId  the value for procedure_dialog.manager_id
	 * @mbg.generated
	 */
	public void setManagerId(String managerId) {
		this.managerId = managerId == null ? null : managerId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column procedure_dialog.key
	 * @return  the value of procedure_dialog.key
	 * @mbg.generated
	 */
	public String getKey() {
		return key;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column procedure_dialog.key
	 * @param key  the value for procedure_dialog.key
	 * @mbg.generated
	 */
	public void setKey(String key) {
		this.key = key == null ? null : key.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column procedure_dialog.data
	 * @return  the value of procedure_dialog.data
	 * @mbg.generated
	 */
	public String getData() {
		return data;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column procedure_dialog.data
	 * @param data  the value for procedure_dialog.data
	 * @mbg.generated
	 */
	public void setData(String data) {
		this.data = data == null ? null : data.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column procedure_dialog.create_time
	 * @return  the value of procedure_dialog.create_time
	 * @mbg.generated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column procedure_dialog.create_time
	 * @param createTime  the value for procedure_dialog.create_time
	 * @mbg.generated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column procedure_dialog.update_time
	 * @return  the value of procedure_dialog.update_time
	 * @mbg.generated
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column procedure_dialog.update_time
	 * @param updateTime  the value for procedure_dialog.update_time
	 * @mbg.generated
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column procedure_dialog.in_use
	 * @return  the value of procedure_dialog.in_use
	 * @mbg.generated
	 */
	public Integer getInUse() {
		return inUse;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column procedure_dialog.in_use
	 * @param inUse  the value for procedure_dialog.in_use
	 * @mbg.generated
	 */
	public void setInUse(Integer inUse) {
		this.inUse = inUse;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table procedure_dialog
	 * @mbg.generated
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		ProcedureDialog other = (ProcedureDialog) that;
		return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
				&& (this.getDialogId() == null ? other.getDialogId() == null
						: this.getDialogId().equals(other.getDialogId()))
				&& (this.getProcedureId() == null ? other.getProcedureId() == null
						: this.getProcedureId().equals(other.getProcedureId()))
				&& (this.getManagerId() == null ? other.getManagerId() == null
						: this.getManagerId().equals(other.getManagerId()))
				&& (this.getKey() == null ? other.getKey() == null : this.getKey().equals(other.getKey()))
				&& (this.getData() == null ? other.getData() == null : this.getData().equals(other.getData()))
				&& (this.getCreateTime() == null ? other.getCreateTime() == null
						: this.getCreateTime().equals(other.getCreateTime()))
				&& (this.getUpdateTime() == null ? other.getUpdateTime() == null
						: this.getUpdateTime().equals(other.getUpdateTime()))
				&& (this.getInUse() == null ? other.getInUse() == null : this.getInUse().equals(other.getInUse()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table procedure_dialog
	 * @mbg.generated
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result + ((getDialogId() == null) ? 0 : getDialogId().hashCode());
		result = prime * result + ((getProcedureId() == null) ? 0 : getProcedureId().hashCode());
		result = prime * result + ((getManagerId() == null) ? 0 : getManagerId().hashCode());
		result = prime * result + ((getKey() == null) ? 0 : getKey().hashCode());
		result = prime * result + ((getData() == null) ? 0 : getData().hashCode());
		result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
		result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
		result = prime * result + ((getInUse() == null) ? 0 : getInUse().hashCode());
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table procedure_dialog
	 * @mbg.generated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", dialogId=").append(dialogId);
		sb.append(", procedureId=").append(procedureId);
		sb.append(", managerId=").append(managerId);
		sb.append(", key=").append(key);
		sb.append(", data=").append(data);
		sb.append(", createTime=").append(createTime);
		sb.append(", updateTime=").append(updateTime);
		sb.append(", inUse=").append(inUse);
		sb.append("]");
		return sb.toString();
	}

	/**
	 * 
	 */
	private static final long serialVersionUID = 1109927812974128066L;
}