package com.lifelight.api.vo;

import java.io.Serializable;
import java.util.Date;

public class ApiUserInvoiceVO implements Serializable{

    /**
	 * 
	 */
	private static final long serialVersionUID = 6582605841649886869L;

	private Integer id;

    private String managerId;

    private String invoiceType;

    private String invoiceTitleType;

    private String taxpayer;

    private String taxpayerNumber;

    private String ticketCollectorMobile;

    private String ticketCollectorEmail;

    private Date createTime;

    private Date updateTime;

    private Integer inUse;
   

    public Integer getId() {
		return id;
	}



	public void setId(Integer id) {
		this.id = id;
	}



	public String getManagerId() {
		return managerId;
	}



	public void setManagerId(String managerId) {
		this.managerId = managerId;
	}



	public String getInvoiceType() {
		return invoiceType;
	}



	public void setInvoiceType(String invoiceType) {
		this.invoiceType = invoiceType;
	}



	public String getInvoiceTitleType() {
		return invoiceTitleType;
	}



	public void setInvoiceTitleType(String invoiceTitleType) {
		this.invoiceTitleType = invoiceTitleType;
	}



	public String getTaxpayer() {
		return taxpayer;
	}



	public void setTaxpayer(String taxpayer) {
		this.taxpayer = taxpayer;
	}



	public String getTaxpayerNumber() {
		return taxpayerNumber;
	}



	public void setTaxpayerNumber(String taxpayerNumber) {
		this.taxpayerNumber = taxpayerNumber;
	}



	public String getTicketCollectorMobile() {
		return ticketCollectorMobile;
	}



	public void setTicketCollectorMobile(String ticketCollectorMobile) {
		this.ticketCollectorMobile = ticketCollectorMobile;
	}



	public String getTicketCollectorEmail() {
		return ticketCollectorEmail;
	}



	public void setTicketCollectorEmail(String ticketCollectorEmail) {
		this.ticketCollectorEmail = ticketCollectorEmail;
	}



	public Date getCreateTime() {
		return createTime;
	}



	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}



	public Date getUpdateTime() {
		return updateTime;
	}



	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}



	public Integer getInUse() {
		return inUse;
	}



	public void setInUse(Integer inUse) {
		this.inUse = inUse;
	}



	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_user_invoice
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", managerId=").append(managerId);
        sb.append(", invoiceType=").append(invoiceType);
        sb.append(", invoiceTitleType=").append(invoiceTitleType);
        sb.append(", taxpayer=").append(taxpayer);
        sb.append(", taxpayerNumber=").append(taxpayerNumber);
        sb.append(", ticketCollectorMobile=").append(ticketCollectorMobile);
        sb.append(", ticketCollectorEmail=").append(ticketCollectorEmail);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", inUse=").append(inUse);
        sb.append("]");
        return sb.toString();
    }
}